// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/favorite/activity.proto

package favorite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActivityInfo struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32        `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64         `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64         `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string        `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string        `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string        `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string        `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Require              string        `protobuf:"bytes,10,opt,name=require,proto3" json:"require,omitempty"`
	Cover                string        `protobuf:"bytes,11,opt,name=cover,proto3" json:"cover,omitempty"`
	Owner                string        `protobuf:"bytes,12,opt,name=owner,proto3" json:"owner,omitempty"`
	Date                 *DateInfo     `protobuf:"bytes,13,opt,name=date,proto3" json:"date,omitempty"`
	Place                *PlaceInfo    `protobuf:"bytes,14,opt,name=place,proto3" json:"place,omitempty"`
	Organizer            string        `protobuf:"bytes,15,opt,name=organizer,proto3" json:"organizer,omitempty"`
	Limit                uint32        `protobuf:"varint,16,opt,name=limit,proto3" json:"limit,omitempty"`
	Status               uint32        `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
	Show                 uint32        `protobuf:"varint,18,opt,name=show,proto3" json:"show,omitempty"`
	Participant          uint32        `protobuf:"varint,19,opt,name=participant,proto3" json:"participant,omitempty"`
	Template             string        `protobuf:"bytes,20,opt,name=template,proto3" json:"template,omitempty"`
	Prize                *PrizeInfo    `protobuf:"bytes,21,opt,name=prize,proto3" json:"prize,omitempty"`
	Access               uint32        `protobuf:"varint,22,opt,name=access,proto3" json:"access,omitempty"`
	Poster               string        `protobuf:"bytes,23,opt,name=poster,proto3" json:"poster,omitempty"`
	Certify              *CertifyInfo  `protobuf:"bytes,24,opt,name=certify,proto3" json:"certify,omitempty"`
	Way                  *PairInfo     `protobuf:"bytes,25,opt,name=way,proto3" json:"way,omitempty"`
	Scope                uint32        `protobuf:"varint,26,opt,name=scope,proto3" json:"scope,omitempty"`
	Quotes               []string      `protobuf:"bytes,40,rep,name=quotes,proto3" json:"quotes,omitempty"`
	Tags                 []string      `protobuf:"bytes,41,rep,name=tags,proto3" json:"tags,omitempty"`
	Assets               []string      `protobuf:"bytes,42,rep,name=assets,proto3" json:"assets,omitempty"`
	Targets              []string      `protobuf:"bytes,43,rep,name=targets,proto3" json:"targets,omitempty"`
	Opuses               []*OpusInfo   `protobuf:"bytes,44,rep,name=opuses,proto3" json:"opuses,omitempty"`
	Records              []*RecordInfo `protobuf:"bytes,45,rep,name=records,proto3" json:"records,omitempty"`
	Admins               []*PairInfo   `protobuf:"bytes,46,rep,name=admins,proto3" json:"admins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ActivityInfo) Reset()         { *m = ActivityInfo{} }
func (m *ActivityInfo) String() string { return proto.CompactTextString(m) }
func (*ActivityInfo) ProtoMessage()    {}
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{0}
}

func (m *ActivityInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityInfo.Unmarshal(m, b)
}
func (m *ActivityInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityInfo.Marshal(b, m, deterministic)
}
func (m *ActivityInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityInfo.Merge(m, src)
}
func (m *ActivityInfo) XXX_Size() int {
	return xxx_messageInfo_ActivityInfo.Size(m)
}
func (m *ActivityInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityInfo proto.InternalMessageInfo

func (m *ActivityInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ActivityInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActivityInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ActivityInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ActivityInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ActivityInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ActivityInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ActivityInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ActivityInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ActivityInfo) GetRequire() string {
	if m != nil {
		return m.Require
	}
	return ""
}

func (m *ActivityInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ActivityInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ActivityInfo) GetDate() *DateInfo {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ActivityInfo) GetPlace() *PlaceInfo {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *ActivityInfo) GetOrganizer() string {
	if m != nil {
		return m.Organizer
	}
	return ""
}

func (m *ActivityInfo) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ActivityInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ActivityInfo) GetShow() uint32 {
	if m != nil {
		return m.Show
	}
	return 0
}

func (m *ActivityInfo) GetParticipant() uint32 {
	if m != nil {
		return m.Participant
	}
	return 0
}

func (m *ActivityInfo) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *ActivityInfo) GetPrize() *PrizeInfo {
	if m != nil {
		return m.Prize
	}
	return nil
}

func (m *ActivityInfo) GetAccess() uint32 {
	if m != nil {
		return m.Access
	}
	return 0
}

func (m *ActivityInfo) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *ActivityInfo) GetCertify() *CertifyInfo {
	if m != nil {
		return m.Certify
	}
	return nil
}

func (m *ActivityInfo) GetWay() *PairInfo {
	if m != nil {
		return m.Way
	}
	return nil
}

func (m *ActivityInfo) GetScope() uint32 {
	if m != nil {
		return m.Scope
	}
	return 0
}

func (m *ActivityInfo) GetQuotes() []string {
	if m != nil {
		return m.Quotes
	}
	return nil
}

func (m *ActivityInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ActivityInfo) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *ActivityInfo) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ActivityInfo) GetOpuses() []*OpusInfo {
	if m != nil {
		return m.Opuses
	}
	return nil
}

func (m *ActivityInfo) GetRecords() []*RecordInfo {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *ActivityInfo) GetAdmins() []*PairInfo {
	if m != nil {
		return m.Admins
	}
	return nil
}

type CertifyInfo struct {
	Style                string   `protobuf:"bytes,1,opt,name=style,proto3" json:"style,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertifyInfo) Reset()         { *m = CertifyInfo{} }
func (m *CertifyInfo) String() string { return proto.CompactTextString(m) }
func (*CertifyInfo) ProtoMessage()    {}
func (*CertifyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{1}
}

func (m *CertifyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertifyInfo.Unmarshal(m, b)
}
func (m *CertifyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertifyInfo.Marshal(b, m, deterministic)
}
func (m *CertifyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertifyInfo.Merge(m, src)
}
func (m *CertifyInfo) XXX_Size() int {
	return xxx_messageInfo_CertifyInfo.Size(m)
}
func (m *CertifyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CertifyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CertifyInfo proto.InternalMessageInfo

func (m *CertifyInfo) GetStyle() string {
	if m != nil {
		return m.Style
	}
	return ""
}

func (m *CertifyInfo) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PrizeInfo struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string      `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Ranks                []*RankInfo `protobuf:"bytes,3,rep,name=ranks,proto3" json:"ranks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PrizeInfo) Reset()         { *m = PrizeInfo{} }
func (m *PrizeInfo) String() string { return proto.CompactTextString(m) }
func (*PrizeInfo) ProtoMessage()    {}
func (*PrizeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{2}
}

func (m *PrizeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrizeInfo.Unmarshal(m, b)
}
func (m *PrizeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrizeInfo.Marshal(b, m, deterministic)
}
func (m *PrizeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrizeInfo.Merge(m, src)
}
func (m *PrizeInfo) XXX_Size() int {
	return xxx_messageInfo_PrizeInfo.Size(m)
}
func (m *PrizeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PrizeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PrizeInfo proto.InternalMessageInfo

func (m *PrizeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PrizeInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *PrizeInfo) GetRanks() []*RankInfo {
	if m != nil {
		return m.Ranks
	}
	return nil
}

type RankInfo struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankInfo) Reset()         { *m = RankInfo{} }
func (m *RankInfo) String() string { return proto.CompactTextString(m) }
func (*RankInfo) ProtoMessage()    {}
func (*RankInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{3}
}

func (m *RankInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankInfo.Unmarshal(m, b)
}
func (m *RankInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankInfo.Marshal(b, m, deterministic)
}
func (m *RankInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankInfo.Merge(m, src)
}
func (m *RankInfo) XXX_Size() int {
	return xxx_messageInfo_RankInfo.Size(m)
}
func (m *RankInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RankInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RankInfo proto.InternalMessageInfo

func (m *RankInfo) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RankInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RankInfo) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type OpusInfo struct {
	Rank                 uint32   `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpusInfo) Reset()         { *m = OpusInfo{} }
func (m *OpusInfo) String() string { return proto.CompactTextString(m) }
func (*OpusInfo) ProtoMessage()    {}
func (*OpusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{4}
}

func (m *OpusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpusInfo.Unmarshal(m, b)
}
func (m *OpusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpusInfo.Marshal(b, m, deterministic)
}
func (m *OpusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpusInfo.Merge(m, src)
}
func (m *OpusInfo) XXX_Size() int {
	return xxx_messageInfo_OpusInfo.Size(m)
}
func (m *OpusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OpusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OpusInfo proto.InternalMessageInfo

func (m *OpusInfo) GetRank() uint32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *OpusInfo) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *OpusInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *OpusInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReqActivityAdd struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string       `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Remark               string       `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string       `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Type                 int32        `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Operator             string       `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Date                 *DateInfo    `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Place                *PlaceInfo   `protobuf:"bytes,8,opt,name=place,proto3" json:"place,omitempty"`
	Organizer            string       `protobuf:"bytes,9,opt,name=organizer,proto3" json:"organizer,omitempty"`
	Require              string       `protobuf:"bytes,10,opt,name=require,proto3" json:"require,omitempty"`
	Limit                uint32       `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	Show                 uint32       `protobuf:"varint,12,opt,name=show,proto3" json:"show,omitempty"`
	Template             string       `protobuf:"bytes,13,opt,name=template,proto3" json:"template,omitempty"`
	Prize                *PrizeInfo   `protobuf:"bytes,14,opt,name=prize,proto3" json:"prize,omitempty"`
	Status               uint32       `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	Certify              *CertifyInfo `protobuf:"bytes,16,opt,name=certify,proto3" json:"certify,omitempty"`
	Way                  *PairInfo    `protobuf:"bytes,17,opt,name=way,proto3" json:"way,omitempty"`
	Scope                uint32       `protobuf:"varint,18,opt,name=scope,proto3" json:"scope,omitempty"`
	Assets               []string     `protobuf:"bytes,31,rep,name=assets,proto3" json:"assets,omitempty"`
	Tags                 []string     `protobuf:"bytes,32,rep,name=tags,proto3" json:"tags,omitempty"`
	Targets              []string     `protobuf:"bytes,33,rep,name=targets,proto3" json:"targets,omitempty"`
	Quotes               []string     `protobuf:"bytes,40,rep,name=quotes,proto3" json:"quotes,omitempty"`
	Admins               []*PairInfo  `protobuf:"bytes,41,rep,name=admins,proto3" json:"admins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqActivityAdd) Reset()         { *m = ReqActivityAdd{} }
func (m *ReqActivityAdd) String() string { return proto.CompactTextString(m) }
func (*ReqActivityAdd) ProtoMessage()    {}
func (*ReqActivityAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{5}
}

func (m *ReqActivityAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqActivityAdd.Unmarshal(m, b)
}
func (m *ReqActivityAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqActivityAdd.Marshal(b, m, deterministic)
}
func (m *ReqActivityAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqActivityAdd.Merge(m, src)
}
func (m *ReqActivityAdd) XXX_Size() int {
	return xxx_messageInfo_ReqActivityAdd.Size(m)
}
func (m *ReqActivityAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqActivityAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqActivityAdd proto.InternalMessageInfo

func (m *ReqActivityAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqActivityAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqActivityAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqActivityAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqActivityAdd) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqActivityAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqActivityAdd) GetDate() *DateInfo {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ReqActivityAdd) GetPlace() *PlaceInfo {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *ReqActivityAdd) GetOrganizer() string {
	if m != nil {
		return m.Organizer
	}
	return ""
}

func (m *ReqActivityAdd) GetRequire() string {
	if m != nil {
		return m.Require
	}
	return ""
}

func (m *ReqActivityAdd) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReqActivityAdd) GetShow() uint32 {
	if m != nil {
		return m.Show
	}
	return 0
}

func (m *ReqActivityAdd) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *ReqActivityAdd) GetPrize() *PrizeInfo {
	if m != nil {
		return m.Prize
	}
	return nil
}

func (m *ReqActivityAdd) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqActivityAdd) GetCertify() *CertifyInfo {
	if m != nil {
		return m.Certify
	}
	return nil
}

func (m *ReqActivityAdd) GetWay() *PairInfo {
	if m != nil {
		return m.Way
	}
	return nil
}

func (m *ReqActivityAdd) GetScope() uint32 {
	if m != nil {
		return m.Scope
	}
	return 0
}

func (m *ReqActivityAdd) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *ReqActivityAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqActivityAdd) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ReqActivityAdd) GetQuotes() []string {
	if m != nil {
		return m.Quotes
	}
	return nil
}

func (m *ReqActivityAdd) GetAdmins() []*PairInfo {
	if m != nil {
		return m.Admins
	}
	return nil
}

type ReqActivityUpdate struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string       `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string       `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Operator             string       `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Date                 *DateInfo    `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Place                *PlaceInfo   `protobuf:"bytes,7,opt,name=place,proto3" json:"place,omitempty"`
	Organizer            string       `protobuf:"bytes,8,opt,name=organizer,proto3" json:"organizer,omitempty"`
	Require              string       `protobuf:"bytes,9,opt,name=require,proto3" json:"require,omitempty"`
	Limit                uint32       `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Certify              *CertifyInfo `protobuf:"bytes,11,opt,name=certify,proto3" json:"certify,omitempty"`
	Way                  *PairInfo    `protobuf:"bytes,12,opt,name=way,proto3" json:"way,omitempty"`
	Scope                uint32       `protobuf:"varint,13,opt,name=scope,proto3" json:"scope,omitempty"`
	Tags                 []string     `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Targets              []string     `protobuf:"bytes,22,rep,name=targets,proto3" json:"targets,omitempty"`
	Assets               []string     `protobuf:"bytes,23,rep,name=assets,proto3" json:"assets,omitempty"`
	Admins               []*PairInfo  `protobuf:"bytes,30,rep,name=admins,proto3" json:"admins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqActivityUpdate) Reset()         { *m = ReqActivityUpdate{} }
func (m *ReqActivityUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqActivityUpdate) ProtoMessage()    {}
func (*ReqActivityUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{6}
}

func (m *ReqActivityUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqActivityUpdate.Unmarshal(m, b)
}
func (m *ReqActivityUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqActivityUpdate.Marshal(b, m, deterministic)
}
func (m *ReqActivityUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqActivityUpdate.Merge(m, src)
}
func (m *ReqActivityUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqActivityUpdate.Size(m)
}
func (m *ReqActivityUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqActivityUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqActivityUpdate proto.InternalMessageInfo

func (m *ReqActivityUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqActivityUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqActivityUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqActivityUpdate) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqActivityUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqActivityUpdate) GetDate() *DateInfo {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ReqActivityUpdate) GetPlace() *PlaceInfo {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *ReqActivityUpdate) GetOrganizer() string {
	if m != nil {
		return m.Organizer
	}
	return ""
}

func (m *ReqActivityUpdate) GetRequire() string {
	if m != nil {
		return m.Require
	}
	return ""
}

func (m *ReqActivityUpdate) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReqActivityUpdate) GetCertify() *CertifyInfo {
	if m != nil {
		return m.Certify
	}
	return nil
}

func (m *ReqActivityUpdate) GetWay() *PairInfo {
	if m != nil {
		return m.Way
	}
	return nil
}

func (m *ReqActivityUpdate) GetScope() uint32 {
	if m != nil {
		return m.Scope
	}
	return 0
}

func (m *ReqActivityUpdate) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqActivityUpdate) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ReqActivityUpdate) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *ReqActivityUpdate) GetAdmins() []*PairInfo {
	if m != nil {
		return m.Admins
	}
	return nil
}

type ReqActivityPrize struct {
	Uid                  string      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string      `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Operator             string      `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Ranks                []*RankInfo `protobuf:"bytes,15,rep,name=ranks,proto3" json:"ranks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqActivityPrize) Reset()         { *m = ReqActivityPrize{} }
func (m *ReqActivityPrize) String() string { return proto.CompactTextString(m) }
func (*ReqActivityPrize) ProtoMessage()    {}
func (*ReqActivityPrize) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{7}
}

func (m *ReqActivityPrize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqActivityPrize.Unmarshal(m, b)
}
func (m *ReqActivityPrize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqActivityPrize.Marshal(b, m, deterministic)
}
func (m *ReqActivityPrize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqActivityPrize.Merge(m, src)
}
func (m *ReqActivityPrize) XXX_Size() int {
	return xxx_messageInfo_ReqActivityPrize.Size(m)
}
func (m *ReqActivityPrize) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqActivityPrize.DiscardUnknown(m)
}

var xxx_messageInfo_ReqActivityPrize proto.InternalMessageInfo

func (m *ReqActivityPrize) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqActivityPrize) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqActivityPrize) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ReqActivityPrize) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqActivityPrize) GetRanks() []*RankInfo {
	if m != nil {
		return m.Ranks
	}
	return nil
}

type ReqActivityOpuses struct {
	Uid                  string      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string      `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []*OpusInfo `protobuf:"bytes,13,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqActivityOpuses) Reset()         { *m = ReqActivityOpuses{} }
func (m *ReqActivityOpuses) String() string { return proto.CompactTextString(m) }
func (*ReqActivityOpuses) ProtoMessage()    {}
func (*ReqActivityOpuses) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{8}
}

func (m *ReqActivityOpuses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqActivityOpuses.Unmarshal(m, b)
}
func (m *ReqActivityOpuses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqActivityOpuses.Marshal(b, m, deterministic)
}
func (m *ReqActivityOpuses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqActivityOpuses.Merge(m, src)
}
func (m *ReqActivityOpuses) XXX_Size() int {
	return xxx_messageInfo_ReqActivityOpuses.Size(m)
}
func (m *ReqActivityOpuses) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqActivityOpuses.DiscardUnknown(m)
}

var xxx_messageInfo_ReqActivityOpuses proto.InternalMessageInfo

func (m *ReqActivityOpuses) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqActivityOpuses) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqActivityOpuses) GetList() []*OpusInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyActivityInfo struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *ActivityInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyActivityInfo) Reset()         { *m = ReplyActivityInfo{} }
func (m *ReplyActivityInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyActivityInfo) ProtoMessage()    {}
func (*ReplyActivityInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{9}
}

func (m *ReplyActivityInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyActivityInfo.Unmarshal(m, b)
}
func (m *ReplyActivityInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyActivityInfo.Marshal(b, m, deterministic)
}
func (m *ReplyActivityInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyActivityInfo.Merge(m, src)
}
func (m *ReplyActivityInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyActivityInfo.Size(m)
}
func (m *ReplyActivityInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyActivityInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyActivityInfo proto.InternalMessageInfo

func (m *ReplyActivityInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyActivityInfo) GetInfo() *ActivityInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyActivityList struct {
	Status               *ReplyStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32          `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32          `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32          `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*ActivityInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyActivityList) Reset()         { *m = ReplyActivityList{} }
func (m *ReplyActivityList) String() string { return proto.CompactTextString(m) }
func (*ReplyActivityList) ProtoMessage()    {}
func (*ReplyActivityList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{10}
}

func (m *ReplyActivityList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyActivityList.Unmarshal(m, b)
}
func (m *ReplyActivityList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyActivityList.Marshal(b, m, deterministic)
}
func (m *ReplyActivityList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyActivityList.Merge(m, src)
}
func (m *ReplyActivityList) XXX_Size() int {
	return xxx_messageInfo_ReplyActivityList.Size(m)
}
func (m *ReplyActivityList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyActivityList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyActivityList proto.InternalMessageInfo

func (m *ReplyActivityList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyActivityList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyActivityList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyActivityList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyActivityList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyActivityList) GetList() []*ActivityInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyPairList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*PairInfo  `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyPairList) Reset()         { *m = ReplyPairList{} }
func (m *ReplyPairList) String() string { return proto.CompactTextString(m) }
func (*ReplyPairList) ProtoMessage()    {}
func (*ReplyPairList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d14c73187376933, []int{11}
}

func (m *ReplyPairList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPairList.Unmarshal(m, b)
}
func (m *ReplyPairList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPairList.Marshal(b, m, deterministic)
}
func (m *ReplyPairList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPairList.Merge(m, src)
}
func (m *ReplyPairList) XXX_Size() int {
	return xxx_messageInfo_ReplyPairList.Size(m)
}
func (m *ReplyPairList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPairList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPairList proto.InternalMessageInfo

func (m *ReplyPairList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPairList) GetList() []*PairInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ActivityInfo)(nil), "omo.msp.favorite.ActivityInfo")
	proto.RegisterType((*CertifyInfo)(nil), "omo.msp.favorite.CertifyInfo")
	proto.RegisterType((*PrizeInfo)(nil), "omo.msp.favorite.PrizeInfo")
	proto.RegisterType((*RankInfo)(nil), "omo.msp.favorite.RankInfo")
	proto.RegisterType((*OpusInfo)(nil), "omo.msp.favorite.OpusInfo")
	proto.RegisterType((*ReqActivityAdd)(nil), "omo.msp.favorite.ReqActivityAdd")
	proto.RegisterType((*ReqActivityUpdate)(nil), "omo.msp.favorite.ReqActivityUpdate")
	proto.RegisterType((*ReqActivityPrize)(nil), "omo.msp.favorite.ReqActivityPrize")
	proto.RegisterType((*ReqActivityOpuses)(nil), "omo.msp.favorite.ReqActivityOpuses")
	proto.RegisterType((*ReplyActivityInfo)(nil), "omo.msp.favorite.ReplyActivityInfo")
	proto.RegisterType((*ReplyActivityList)(nil), "omo.msp.favorite.ReplyActivityList")
	proto.RegisterType((*ReplyPairList)(nil), "omo.msp.favorite.ReplyPairList")
}

func init() {
	proto.RegisterFile("proto/favorite/activity.proto", fileDescriptor_3d14c73187376933)
}

var fileDescriptor_3d14c73187376933 = []byte{
	// 1335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdb, 0x72, 0x23, 0x35,
	0x10, 0x5d, 0xdf, 0x6d, 0xf9, 0x12, 0xaf, 0xd8, 0x8b, 0xf0, 0xde, 0xcc, 0xec, 0x8b, 0x17, 0x16,
	0x2f, 0x84, 0x02, 0x8a, 0xc7, 0x2c, 0x14, 0xa9, 0x5d, 0xb2, 0x24, 0x4c, 0xd8, 0x2a, 0x8a, 0x27,
	0x26, 0x33, 0x4a, 0x50, 0xc5, 0x9e, 0x99, 0x48, 0xb2, 0x83, 0xf7, 0x81, 0x0f, 0xe1, 0x17, 0xf8,
	0x0a, 0xbe, 0x81, 0x2a, 0x7e, 0x07, 0x4a, 0x2d, 0xc9, 0x91, 0x2f, 0xe3, 0x4b, 0xc2, 0x9b, 0x5a,
	0x6a, 0x9d, 0x6e, 0x75, 0x1f, 0x1d, 0x4d, 0x0d, 0x7a, 0x94, 0xf2, 0x44, 0x26, 0x2f, 0x4e, 0x83,
	0x71, 0xc2, 0x99, 0xa4, 0x2f, 0x82, 0x50, 0xb2, 0x31, 0x93, 0x93, 0x3e, 0xcc, 0xe3, 0x76, 0x32,
	0x4c, 0xfa, 0x43, 0x91, 0xf6, 0xad, 0x43, 0xe7, 0xc1, 0xdc, 0x86, 0x30, 0x19, 0x0e, 0x93, 0x58,
	0xbb, 0x7b, 0xff, 0x56, 0x50, 0x63, 0xcf, 0x20, 0xbc, 0x8a, 0x4f, 0x13, 0xdc, 0x46, 0x85, 0x11,
	0x8b, 0x48, 0xae, 0x9b, 0xeb, 0xd5, 0x7c, 0x35, 0xc4, 0x2d, 0x94, 0x67, 0x11, 0xc9, 0x77, 0x73,
	0xbd, 0xa2, 0x9f, 0x67, 0x11, 0xc6, 0xa8, 0x28, 0x27, 0x29, 0x25, 0x85, 0x6e, 0xae, 0xd7, 0xf4,
	0x61, 0x8c, 0x09, 0xaa, 0x84, 0x9c, 0x06, 0x92, 0x46, 0xa4, 0xd8, 0xcd, 0xf5, 0x0a, 0xbe, 0x35,
	0xd5, 0xca, 0x28, 0x8d, 0x60, 0xa5, 0xa4, 0x57, 0x8c, 0x39, 0xdd, 0x93, 0x70, 0x52, 0x86, 0x68,
	0xd6, 0xc4, 0x1d, 0x54, 0x4d, 0x52, 0xca, 0x61, 0xa9, 0x02, 0x4b, 0x53, 0x5b, 0x45, 0x8f, 0x83,
	0x21, 0x25, 0x55, 0x98, 0x87, 0x31, 0xbe, 0x87, 0xca, 0x9c, 0x0e, 0x03, 0x7e, 0x4e, 0x6a, 0x30,
	0x6b, 0x2c, 0x15, 0x81, 0xd3, 0x8b, 0x11, 0xe3, 0x94, 0x20, 0x1d, 0xc1, 0x98, 0xf8, 0x0e, 0x2a,
	0x85, 0xc9, 0x98, 0x72, 0x52, 0x87, 0x79, 0x6d, 0xa8, 0xd9, 0xe4, 0x32, 0xa6, 0x9c, 0x34, 0xf4,
	0x2c, 0x18, 0xb8, 0x8f, 0x8a, 0x2a, 0x61, 0xd2, 0xec, 0xe6, 0x7a, 0xf5, 0xdd, 0x4e, 0x7f, 0xbe,
	0xc0, 0xfd, 0x6f, 0x02, 0x49, 0x55, 0xed, 0x7c, 0xf0, 0xc3, 0x9f, 0xa2, 0x52, 0x3a, 0x08, 0x42,
	0x4a, 0x5a, 0xb0, 0xe1, 0xc1, 0xe2, 0x86, 0x23, 0xb5, 0x0c, 0x3b, 0xb4, 0x27, 0x7e, 0x88, 0x6a,
	0x09, 0x3f, 0x0b, 0x62, 0xf6, 0x8e, 0x72, 0xb2, 0x03, 0xc1, 0xaf, 0x26, 0x54, 0x5a, 0x03, 0x36,
	0x64, 0x92, 0xb4, 0xa1, 0xe2, 0xda, 0x50, 0x87, 0x16, 0x32, 0x90, 0x23, 0x41, 0x6e, 0xc3, 0xb4,
	0xb1, 0x54, 0x81, 0xc4, 0xaf, 0xc9, 0x25, 0xc1, 0xba, 0x3d, 0x6a, 0x8c, 0xbb, 0xa8, 0x9e, 0x06,
	0x5c, 0xb2, 0x90, 0xa5, 0x41, 0x2c, 0xc9, 0x7b, 0xb0, 0xe4, 0x4e, 0xa9, 0x92, 0x4b, 0x3a, 0x4c,
	0x07, 0xea, 0xa0, 0x77, 0x74, 0xc9, 0xad, 0x0d, 0x07, 0xe2, 0xec, 0x1d, 0x25, 0x77, 0x33, 0x0f,
	0xa4, 0x96, 0xcd, 0x81, 0xd4, 0x50, 0x25, 0x17, 0x84, 0x21, 0x15, 0x82, 0xdc, 0xd3, 0xc9, 0x69,
	0x4b, 0xcd, 0xa7, 0x89, 0x90, 0x94, 0x93, 0xfb, 0xba, 0x53, 0xda, 0xc2, 0x5f, 0xa2, 0x4a, 0x48,
	0xb9, 0x64, 0xa7, 0x13, 0x42, 0x20, 0xc8, 0xa3, 0xc5, 0x20, 0x5f, 0x6b, 0x07, 0x08, 0x63, 0xbd,
	0xf1, 0x73, 0x54, 0xb8, 0x0c, 0x26, 0xe4, 0xfd, 0xac, 0xde, 0x1c, 0x05, 0x8c, 0xc3, 0x0e, 0xe5,
	0xa6, 0x2a, 0x29, 0xc2, 0x24, 0xa5, 0xa4, 0xa3, 0x2b, 0x09, 0x86, 0x4a, 0xea, 0x62, 0x94, 0x48,
	0x2a, 0x48, 0xaf, 0x5b, 0x50, 0x49, 0x69, 0x0b, 0x88, 0x1e, 0x9c, 0x09, 0xf2, 0x0c, 0x66, 0x61,
	0x0c, 0x07, 0x13, 0x82, 0x4a, 0x41, 0x3e, 0xd4, 0xbe, 0xda, 0x52, 0x54, 0x93, 0x01, 0x3f, 0x53,
	0x0b, 0x1f, 0xc1, 0x82, 0x35, 0xf1, 0x2e, 0x2a, 0x27, 0xe9, 0x48, 0x50, 0x41, 0x9e, 0x77, 0x0b,
	0xcb, 0x93, 0x3c, 0x4c, 0x47, 0x02, 0x92, 0x34, 0x9e, 0xf8, 0x0b, 0x45, 0xdc, 0x30, 0xe1, 0x91,
	0x20, 0x1f, 0xc3, 0xa6, 0x87, 0x8b, 0x9b, 0x7c, 0x70, 0xd0, 0xd5, 0x30, 0xce, 0x2a, 0x56, 0x10,
	0x0d, 0x59, 0x2c, 0x48, 0x3f, 0x2b, 0xd6, 0xb4, 0x20, 0xc6, 0xd3, 0xfb, 0x0a, 0xd5, 0x9d, 0xca,
	0x42, 0x89, 0xe4, 0x64, 0x40, 0x8d, 0x02, 0x68, 0xe3, 0x8a, 0x82, 0x79, 0x87, 0x82, 0x1e, 0x45,
	0xb5, 0x69, 0xe7, 0xa7, 0x17, 0x33, 0xe7, 0x5c, 0x4c, 0x8c, 0x8a, 0x11, 0x15, 0x21, 0xec, 0xaa,
	0xf9, 0x30, 0xc6, 0x9f, 0xa0, 0x12, 0x0f, 0xe2, 0x73, 0x41, 0x0a, 0x59, 0x29, 0xfa, 0x41, 0x7c,
	0xae, 0xc9, 0x04, 0x8e, 0xde, 0x6b, 0x54, 0xb5, 0x53, 0x2a, 0x11, 0x16, 0x47, 0xf4, 0x37, 0x08,
	0xd3, 0xf4, 0xb5, 0x31, 0x8d, 0x9d, 0x77, 0x62, 0xc3, 0x15, 0x1f, 0xc5, 0xd2, 0xe8, 0x94, 0x36,
	0xbc, 0x5f, 0x50, 0xd5, 0x56, 0x5b, 0xed, 0x52, 0x01, 0x0c, 0x14, 0x8c, 0xd5, 0x2e, 0xe8, 0xa8,
	0x81, 0xd2, 0x86, 0x23, 0x30, 0x85, 0x19, 0x81, 0xb1, 0x71, 0x8b, 0x57, 0x71, 0xbd, 0xbf, 0x4b,
	0xa8, 0xe5, 0xd3, 0x0b, 0x2b, 0xaa, 0x7b, 0x51, 0xb4, 0xb4, 0x34, 0x53, 0xad, 0xc9, 0xbb, 0x5a,
	0x93, 0x15, 0x68, 0xaa, 0x57, 0x45, 0x57, 0xaf, 0xac, 0x12, 0x2b, 0x61, 0x2d, 0x19, 0x25, 0x76,
	0xb5, 0xb3, 0x3c, 0xa7, 0x9d, 0x56, 0xc9, 0x2a, 0xdb, 0x2a, 0x59, 0xf5, 0x7a, 0x4a, 0x56, 0x9b,
	0x57, 0xb2, 0x95, 0x82, 0xac, 0x09, 0x56, 0x77, 0x35, 0xce, 0x6a, 0x59, 0xc3, 0xd1, 0x32, 0x57,
	0xa9, 0x9a, 0x59, 0x4a, 0xd5, 0xda, 0x46, 0xa9, 0x8c, 0x8c, 0xee, 0xcc, 0xc8, 0xa8, 0xa3, 0x48,
	0xed, 0xeb, 0x28, 0xd2, 0xed, 0x2d, 0x15, 0x09, 0xcf, 0x29, 0x92, 0x51, 0x99, 0x27, 0x33, 0x2a,
	0x63, 0x15, 0xa9, 0xeb, 0x28, 0x92, 0xa3, 0x3c, 0x1f, 0xcc, 0x2a, 0x4f, 0x96, 0xae, 0x5d, 0xa9,
	0xc4, 0xb3, 0x8d, 0x55, 0xe2, 0xcf, 0x22, 0xba, 0xed, 0xb0, 0xfa, 0x2d, 0xbc, 0xe1, 0x4b, 0x3e,
	0x16, 0x96, 0xdd, 0xc4, 0xed, 0x48, 0xed, 0x12, 0xb8, 0x94, 0x41, 0xe0, 0xf2, 0xb6, 0x04, 0xae,
	0x5c, 0x8f, 0xc0, 0xd5, 0x15, 0x04, 0xae, 0x65, 0x10, 0x18, 0xb9, 0x04, 0x76, 0x58, 0x54, 0xbf,
	0x0e, 0x8b, 0x1a, 0x5b, 0xb2, 0xa8, 0xe9, 0xb2, 0xc8, 0xb2, 0xe5, 0xee, 0x72, 0xb6, 0xdc, 0x5b,
	0x60, 0x8b, 0xe1, 0xdc, 0xfd, 0x19, 0xce, 0x5d, 0xb1, 0xe5, 0xf1, 0xc6, 0x6c, 0xf9, 0x23, 0x87,
	0xda, 0x0e, 0x5b, 0xe0, 0xd2, 0x6d, 0x48, 0x16, 0xfb, 0x64, 0x14, 0x9c, 0x27, 0xc3, 0xa5, 0x44,
	0x71, 0x8e, 0x12, 0xd3, 0xe7, 0x64, 0x67, 0xd3, 0xe7, 0xe4, 0x62, 0x86, 0xc9, 0x87, 0xfa, 0xc5,
	0x5d, 0x4c, 0xce, 0x0d, 0x9a, 0x5f, 0xe4, 0xe1, 0x80, 0x09, 0x49, 0x9a, 0x6b, 0x5f, 0x74, 0xf0,
	0xf3, 0x7e, 0x57, 0x21, 0xd3, 0xc1, 0x64, 0xe6, 0x4b, 0xfb, 0xf3, 0xa9, 0xf2, 0xe4, 0xb2, 0xa8,
	0x01, 0x9b, 0x8e, 0xc1, 0x69, 0x2a, 0x4c, 0xbb, 0xa8, 0xc8, 0xe2, 0xd3, 0x04, 0x72, 0xaa, 0xef,
	0x3e, 0x5e, 0xdc, 0xe4, 0x06, 0xf1, 0xc1, 0xd7, 0xfb, 0x27, 0x37, 0x97, 0xc0, 0x01, 0x13, 0xf2,
	0xba, 0x09, 0xdc, 0x41, 0x25, 0x99, 0xc8, 0x60, 0x60, 0xbf, 0x05, 0xc0, 0x50, 0xb3, 0x69, 0x70,
	0x46, 0x85, 0x7d, 0x6e, 0xc1, 0x50, 0xdd, 0x54, 0x03, 0xe8, 0x5a, 0xd3, 0x87, 0xb1, 0x22, 0x5a,
	0x3c, 0x1a, 0x9e, 0x50, 0x7d, 0xbd, 0x9b, 0xbe, 0xb1, 0xd4, 0xc1, 0xa0, 0xa8, 0x6d, 0x28, 0xea,
	0xda, 0x83, 0x41, 0x61, 0xc7, 0xa8, 0x09, 0x29, 0x2a, 0x06, 0xde, 0xe4, 0x4c, 0xb6, 0xa1, 0xf9,
	0xb5, 0x14, 0x07, 0xbf, 0xdd, 0xbf, 0xea, 0x68, 0xc7, 0xa6, 0x73, 0x4c, 0xf9, 0x98, 0x85, 0x14,
	0xff, 0x80, 0xca, 0x7b, 0x51, 0x74, 0x18, 0x53, 0xdc, 0x5d, 0x16, 0xd4, 0xfd, 0x22, 0xe8, 0x3c,
	0xcd, 0x48, 0xcb, 0x3d, 0xa2, 0x77, 0x0b, 0x7f, 0x8f, 0xca, 0xfb, 0x54, 0x2a, 0xc8, 0xa5, 0xe7,
	0xb8, 0x18, 0x51, 0x21, 0x95, 0xeb, 0xa6, 0x78, 0x87, 0xa8, 0xb2, 0x4f, 0x25, 0x14, 0xea, 0x86,
	0x80, 0x0a, 0xc3, 0xbb, 0x85, 0xdf, 0xa2, 0xfa, 0x3e, 0x95, 0x2f, 0x27, 0xdf, 0xb2, 0x81, 0xfa,
	0x8c, 0x7f, 0x92, 0x09, 0xaa, 0x1d, 0x36, 0x85, 0x3d, 0x46, 0x8d, 0x7d, 0x2a, 0x55, 0x8f, 0x98,
	0x90, 0x2c, 0x5c, 0x8f, 0xdb, 0x5d, 0xd1, 0x66, 0x80, 0xf0, 0x6e, 0xe1, 0x23, 0xd4, 0xd2, 0xcf,
	0xd6, 0x06, 0xe9, 0x6a, 0xc7, 0xce, 0x83, 0x0c, 0x58, 0x53, 0xce, 0x9f, 0x10, 0x32, 0x88, 0x81,
	0xa0, 0xf8, 0xe9, 0xca, 0xae, 0x1b, 0xc4, 0x0d, 0x1b, 0xf5, 0xda, 0x22, 0xff, 0xa8, 0x44, 0x3b,
	0xbb, 0x57, 0xaa, 0x5e, 0x99, 0x59, 0x9a, 0x62, 0x1e, 0xa0, 0x86, 0xc6, 0xda, 0xd3, 0x82, 0x7e,
	0x33, 0xb4, 0x37, 0xa8, 0x69, 0x33, 0xd3, 0xef, 0xc6, 0x4d, 0xe1, 0x4c, 0x72, 0xfa, 0x42, 0xe2,
	0xc7, 0x99, 0x68, 0xca, 0x61, 0x6d, 0x47, 0xbe, 0xb3, 0x75, 0x3b, 0x56, 0x9f, 0x8a, 0x37, 0x04,
	0x7b, 0x85, 0x6a, 0x3e, 0x1d, 0x26, 0x63, 0xba, 0xc1, 0x05, 0x5c, 0x03, 0xf5, 0x06, 0xd5, 0xf6,
	0xd2, 0x94, 0xc6, 0xd1, 0x06, 0x50, 0x4f, 0x32, 0xa0, 0xac, 0xc6, 0xc1, 0x3d, 0xae, 0x1f, 0x8f,
	0x4e, 0x24, 0x0f, 0x42, 0xf9, 0xff, 0x00, 0xfa, 0xb6, 0x0d, 0xe6, 0x39, 0x5c, 0xcd, 0x65, 0xed,
	0xb4, 0xee, 0xcc, 0x47, 0xa8, 0xae, 0x31, 0xf5, 0xf3, 0xef, 0xad, 0x84, 0x04, 0x9f, 0x75, 0x88,
	0x07, 0x08, 0x81, 0x2c, 0x70, 0x16, 0x9f, 0x89, 0xf5, 0xa2, 0xb0, 0x9a, 0x7a, 0x2f, 0xdb, 0x3f,
	0xb7, 0x66, 0xff, 0x8c, 0x9d, 0x94, 0xc1, 0xfe, 0xec, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03,
	0x5d, 0x9d, 0x80, 0x63, 0x13, 0x00, 0x00,
}
