// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/favorite/article.proto

package favorite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArticleInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Body                 string   `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	Subtitle             string   `protobuf:"bytes,10,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Owner                string   `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	Status               uint32   `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Targets              []string `protobuf:"bytes,13,rep,name=targets,proto3" json:"targets,omitempty"`
	Assets               []string `protobuf:"bytes,14,rep,name=assets,proto3" json:"assets,omitempty"`
	Tags                 []string `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f089b0f7c4866fe, []int{0}
}

func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (m *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(m, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ArticleInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ArticleInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ArticleInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ArticleInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ArticleInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ArticleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArticleInfo) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ArticleInfo) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *ArticleInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ArticleInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ArticleInfo) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ArticleInfo) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *ArticleInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqArticleAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle             string   `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Assets               []string `protobuf:"bytes,6,rep,name=assets,proto3" json:"assets,omitempty"`
	Targets              []string `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqArticleAdd) Reset()         { *m = ReqArticleAdd{} }
func (m *ReqArticleAdd) String() string { return proto.CompactTextString(m) }
func (*ReqArticleAdd) ProtoMessage()    {}
func (*ReqArticleAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f089b0f7c4866fe, []int{1}
}

func (m *ReqArticleAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqArticleAdd.Unmarshal(m, b)
}
func (m *ReqArticleAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqArticleAdd.Marshal(b, m, deterministic)
}
func (m *ReqArticleAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqArticleAdd.Merge(m, src)
}
func (m *ReqArticleAdd) XXX_Size() int {
	return xxx_messageInfo_ReqArticleAdd.Size(m)
}
func (m *ReqArticleAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqArticleAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqArticleAdd proto.InternalMessageInfo

func (m *ReqArticleAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqArticleAdd) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *ReqArticleAdd) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ReqArticleAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqArticleAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqArticleAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqArticleAdd) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *ReqArticleAdd) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type ReqArticleUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle             string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Targets              []string `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqArticleUpdate) Reset()         { *m = ReqArticleUpdate{} }
func (m *ReqArticleUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqArticleUpdate) ProtoMessage()    {}
func (*ReqArticleUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f089b0f7c4866fe, []int{2}
}

func (m *ReqArticleUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqArticleUpdate.Unmarshal(m, b)
}
func (m *ReqArticleUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqArticleUpdate.Marshal(b, m, deterministic)
}
func (m *ReqArticleUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqArticleUpdate.Merge(m, src)
}
func (m *ReqArticleUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqArticleUpdate.Size(m)
}
func (m *ReqArticleUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqArticleUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqArticleUpdate proto.InternalMessageInfo

func (m *ReqArticleUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqArticleUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqArticleUpdate) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *ReqArticleUpdate) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ReqArticleUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqArticleUpdate) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqArticleUpdate) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type ReqArticleState struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqArticleState) Reset()         { *m = ReqArticleState{} }
func (m *ReqArticleState) String() string { return proto.CompactTextString(m) }
func (*ReqArticleState) ProtoMessage()    {}
func (*ReqArticleState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f089b0f7c4866fe, []int{3}
}

func (m *ReqArticleState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqArticleState.Unmarshal(m, b)
}
func (m *ReqArticleState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqArticleState.Marshal(b, m, deterministic)
}
func (m *ReqArticleState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqArticleState.Merge(m, src)
}
func (m *ReqArticleState) XXX_Size() int {
	return xxx_messageInfo_ReqArticleState.Size(m)
}
func (m *ReqArticleState) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqArticleState.DiscardUnknown(m)
}

var xxx_messageInfo_ReqArticleState proto.InternalMessageInfo

func (m *ReqArticleState) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqArticleState) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqArticleState) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyArticleInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *ArticleInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyArticleInfo) Reset()         { *m = ReplyArticleInfo{} }
func (m *ReplyArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyArticleInfo) ProtoMessage()    {}
func (*ReplyArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f089b0f7c4866fe, []int{4}
}

func (m *ReplyArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyArticleInfo.Unmarshal(m, b)
}
func (m *ReplyArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyArticleInfo.Marshal(b, m, deterministic)
}
func (m *ReplyArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyArticleInfo.Merge(m, src)
}
func (m *ReplyArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyArticleInfo.Size(m)
}
func (m *ReplyArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyArticleInfo proto.InternalMessageInfo

func (m *ReplyArticleInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyArticleInfo) GetInfo() *ArticleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyArticleList struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*ArticleInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyArticleList) Reset()         { *m = ReplyArticleList{} }
func (m *ReplyArticleList) String() string { return proto.CompactTextString(m) }
func (*ReplyArticleList) ProtoMessage()    {}
func (*ReplyArticleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f089b0f7c4866fe, []int{5}
}

func (m *ReplyArticleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyArticleList.Unmarshal(m, b)
}
func (m *ReplyArticleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyArticleList.Marshal(b, m, deterministic)
}
func (m *ReplyArticleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyArticleList.Merge(m, src)
}
func (m *ReplyArticleList) XXX_Size() int {
	return xxx_messageInfo_ReplyArticleList.Size(m)
}
func (m *ReplyArticleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyArticleList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyArticleList proto.InternalMessageInfo

func (m *ReplyArticleList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyArticleList) GetList() []*ArticleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ArticleInfo)(nil), "omo.msp.favorite.ArticleInfo")
	proto.RegisterType((*ReqArticleAdd)(nil), "omo.msp.favorite.ReqArticleAdd")
	proto.RegisterType((*ReqArticleUpdate)(nil), "omo.msp.favorite.ReqArticleUpdate")
	proto.RegisterType((*ReqArticleState)(nil), "omo.msp.favorite.ReqArticleState")
	proto.RegisterType((*ReplyArticleInfo)(nil), "omo.msp.favorite.ReplyArticleInfo")
	proto.RegisterType((*ReplyArticleList)(nil), "omo.msp.favorite.ReplyArticleList")
}

func init() {
	proto.RegisterFile("proto/favorite/article.proto", fileDescriptor_8f089b0f7c4866fe)
}

var fileDescriptor_8f089b0f7c4866fe = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdd, 0x6e, 0xda, 0x30,
	0x14, 0xc7, 0x9b, 0x0f, 0x02, 0x98, 0x42, 0x91, 0x35, 0x4d, 0x16, 0xdd, 0xd4, 0x2c, 0x57, 0x5c,
	0x51, 0xad, 0xd3, 0x1e, 0x80, 0x5e, 0xac, 0xea, 0xd4, 0xaa, 0x53, 0xba, 0x0f, 0x69, 0x77, 0x81,
	0x98, 0x2a, 0x12, 0x89, 0xd3, 0xd8, 0x30, 0x21, 0xed, 0xa9, 0xf6, 0x1a, 0x7b, 0x89, 0xdd, 0xec,
	0x3d, 0x26, 0x1f, 0x27, 0xc1, 0x61, 0x04, 0x90, 0xb8, 0xf3, 0xf1, 0x39, 0xfe, 0x9f, 0xff, 0xcf,
	0xf1, 0x01, 0xf4, 0x2a, 0xcd, 0x98, 0x60, 0x97, 0xb3, 0x60, 0xc9, 0xb2, 0x48, 0xd0, 0xcb, 0x20,
	0x13, 0xd1, 0x74, 0x4e, 0x47, 0xb0, 0x8d, 0xfb, 0x2c, 0x66, 0xa3, 0x98, 0xa7, 0xa3, 0x22, 0x3f,
	0x38, 0xdf, 0xa8, 0x9f, 0xb2, 0x38, 0x66, 0x89, 0x2a, 0xf7, 0xfe, 0x9a, 0xa8, 0x33, 0x56, 0x02,
	0xb7, 0xc9, 0x8c, 0xe1, 0x3e, 0xb2, 0x16, 0x51, 0x48, 0x0c, 0xd7, 0x18, 0xb6, 0x7d, 0xb9, 0xc4,
	0x3d, 0x64, 0x46, 0x21, 0x31, 0x5d, 0x63, 0x68, 0xfb, 0x66, 0x14, 0x62, 0x8c, 0x6c, 0xb1, 0x4a,
	0x29, 0xb1, 0x5c, 0x63, 0xd8, 0xf5, 0x61, 0x8d, 0x09, 0x6a, 0x4e, 0x33, 0x1a, 0x08, 0x1a, 0x12,
	0xdb, 0x35, 0x86, 0x96, 0x5f, 0x84, 0x32, 0xb3, 0x48, 0x43, 0xc8, 0x34, 0x54, 0x26, 0x0f, 0xcb,
	0x33, 0x2c, 0x23, 0x0e, 0x74, 0x2b, 0x42, 0x3c, 0x40, 0x2d, 0x96, 0xd2, 0x0c, 0x52, 0x4d, 0x48,
	0x95, 0xb1, 0xec, 0x9e, 0x04, 0x31, 0x25, 0x2d, 0xd8, 0x87, 0xb5, 0xdc, 0x9b, 0xb0, 0x70, 0x45,
	0xda, 0x6a, 0x4f, 0xae, 0xa5, 0x06, 0x5f, 0x4c, 0x44, 0x24, 0xe6, 0x94, 0x20, 0xa5, 0x51, 0xc4,
	0xf8, 0x05, 0x6a, 0xb0, 0x1f, 0x09, 0xcd, 0x48, 0x07, 0x12, 0x2a, 0xc0, 0x2f, 0x91, 0xc3, 0x45,
	0x20, 0x16, 0x9c, 0x9c, 0x02, 0x59, 0x1e, 0x49, 0x9f, 0x22, 0xc8, 0x9e, 0xa8, 0xe0, 0xa4, 0xeb,
	0x5a, 0xd2, 0x67, 0x1e, 0xca, 0x13, 0x01, 0xe7, 0x32, 0xd1, 0x83, 0x44, 0x1e, 0xc1, 0x0d, 0x05,
	0x4f, 0x9c, 0x9c, 0xc1, 0x2e, 0xac, 0xbd, 0xdf, 0x06, 0xea, 0xfa, 0xf4, 0x39, 0xbf, 0xea, 0x71,
	0x18, 0x96, 0x24, 0x86, 0x46, 0xa2, 0xbb, 0x36, 0x37, 0x5c, 0x17, 0x94, 0x96, 0x46, 0x59, 0x92,
	0xd8, 0x3a, 0x89, 0x7e, 0x7f, 0x8d, 0xff, 0xef, 0x0f, 0xbc, 0xb5, 0xd6, 0xde, 0x34, 0x0e, 0xa7,
	0xc2, 0xa1, 0x91, 0x37, 0x2b, 0xe4, 0xde, 0x2f, 0x03, 0xf5, 0xd7, 0x34, 0x5f, 0xe0, 0x8b, 0x6e,
	0x79, 0x3a, 0x05, 0xa2, 0x59, 0x83, 0x68, 0xd5, 0x20, 0xda, 0xd5, 0x0f, 0xb9, 0x17, 0xa6, 0xa9,
	0xc1, 0x68, 0xa6, 0x9d, 0xaa, 0xe9, 0x6f, 0xe8, 0x6c, 0xed, 0xf9, 0x51, 0x6c, 0xb7, 0xbc, 0x7e,
	0x05, 0x66, 0xe5, 0x15, 0xe8, 0x36, 0xac, 0xaa, 0x0d, 0xef, 0xa7, 0xbc, 0x8c, 0x74, 0xbe, 0xd2,
	0xe7, 0xe8, 0x7d, 0xa9, 0x23, 0xc5, 0x3b, 0x57, 0xaf, 0x47, 0x9b, 0x73, 0x39, 0x82, 0x33, 0x8f,
	0x50, 0x54, 0xb6, 0x79, 0x8b, 0xec, 0x28, 0x99, 0x31, 0x68, 0xbe, 0xf5, 0x90, 0xd6, 0xc3, 0x87,
	0xd2, 0xcd, 0xee, 0x77, 0x11, 0x17, 0x47, 0x74, 0x9f, 0x47, 0x5c, 0x10, 0xd3, 0xb5, 0x0e, 0xe8,
	0x2e, 0x4b, 0xaf, 0xfe, 0x34, 0x50, 0xaf, 0xb8, 0x52, 0x9a, 0x2d, 0xa3, 0x29, 0xc5, 0x0f, 0xc8,
	0x19, 0x87, 0xe1, 0x43, 0x42, 0xf1, 0xc5, 0xb6, 0xb6, 0xda, 0x0c, 0x0c, 0xbc, 0x1a, 0x5f, 0x5a,
	0x1f, 0xef, 0x04, 0xdf, 0x23, 0xe7, 0x86, 0x0a, 0x29, 0xb8, 0x95, 0xe3, 0x79, 0x41, 0xb9, 0x90,
	0xa5, 0x07, 0xca, 0x7d, 0x42, 0xcd, 0x1b, 0x2a, 0xe0, 0x9e, 0x2e, 0x6a, 0xf5, 0x3e, 0x44, 0x73,
	0x41, 0xb3, 0x7d, 0x8a, 0x52, 0xc4, 0x3b, 0xc1, 0x5f, 0x11, 0x52, 0x33, 0x70, 0x1d, 0x70, 0x8a,
	0xbd, 0x5d, 0xd4, 0xaa, 0xee, 0x40, 0xa7, 0x77, 0xe8, 0x54, 0xd5, 0x8f, 0xd5, 0x40, 0xd6, 0xe3,
	0x4b, 0x23, 0x83, 0xf3, 0x1a, 0xd1, 0x92, 0x3b, 0x57, 0x53, 0x5f, 0x1d, 0xbf, 0xd9, 0xe5, 0x13,
	0xe6, 0x63, 0x9f, 0xe2, 0xc7, 0x82, 0xfb, 0xb3, 0x9c, 0xbc, 0xe3, 0xdc, 0xdd, 0xa3, 0x6e, 0xa1,
	0xa5, 0x7e, 0x5d, 0x8f, 0x93, 0xbb, 0x45, 0x6d, 0x9f, 0xc6, 0x6c, 0x49, 0x0f, 0x78, 0x36, 0xbb,
	0xa5, 0xae, 0xfb, 0xdf, 0x7b, 0xd5, 0x7f, 0xd0, 0x89, 0x03, 0xf1, 0xbb, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xcd, 0x2b, 0x1d, 0xf8, 0x8a, 0x07, 0x00, 0x00,
}
