// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/favorite/display.proto

package favorite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DisplayInfo struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64             `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64             `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Name                 string            `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string            `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Remark               string            `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Creator              string            `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string            `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	Cover                string            `protobuf:"bytes,10,opt,name=cover,proto3" json:"cover,omitempty"`
	Origin               string            `protobuf:"bytes,11,opt,name=origin,proto3" json:"origin,omitempty"`
	Type                 uint32            `protobuf:"varint,12,opt,name=type,proto3" json:"type,omitempty"`
	Meta                 string            `protobuf:"bytes,13,opt,name=meta,proto3" json:"meta,omitempty"`
	Status               uint32            `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	Banner               string            `protobuf:"bytes,15,opt,name=banner,proto3" json:"banner,omitempty"`
	Poster               string            `protobuf:"bytes,16,opt,name=poster,proto3" json:"poster,omitempty"`
	Access               uint32            `protobuf:"varint,17,opt,name=access,proto3" json:"access,omitempty"`
	Tags                 []string          `protobuf:"bytes,30,rep,name=tags,proto3" json:"tags,omitempty"`
	Contents             []*DisplayContent `protobuf:"bytes,31,rep,name=contents,proto3" json:"contents,omitempty"`
	Pending              []*DisplayContent `protobuf:"bytes,32,rep,name=pending,proto3" json:"pending,omitempty"`
	Records              []*RecordInfo     `protobuf:"bytes,41,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DisplayInfo) Reset()         { *m = DisplayInfo{} }
func (m *DisplayInfo) String() string { return proto.CompactTextString(m) }
func (*DisplayInfo) ProtoMessage()    {}
func (*DisplayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{0}
}

func (m *DisplayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisplayInfo.Unmarshal(m, b)
}
func (m *DisplayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisplayInfo.Marshal(b, m, deterministic)
}
func (m *DisplayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisplayInfo.Merge(m, src)
}
func (m *DisplayInfo) XXX_Size() int {
	return xxx_messageInfo_DisplayInfo.Size(m)
}
func (m *DisplayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DisplayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DisplayInfo proto.InternalMessageInfo

func (m *DisplayInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DisplayInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DisplayInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *DisplayInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *DisplayInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DisplayInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DisplayInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *DisplayInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *DisplayInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *DisplayInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *DisplayInfo) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *DisplayInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DisplayInfo) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *DisplayInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DisplayInfo) GetBanner() string {
	if m != nil {
		return m.Banner
	}
	return ""
}

func (m *DisplayInfo) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *DisplayInfo) GetAccess() uint32 {
	if m != nil {
		return m.Access
	}
	return 0
}

func (m *DisplayInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DisplayInfo) GetContents() []*DisplayContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *DisplayInfo) GetPending() []*DisplayContent {
	if m != nil {
		return m.Pending
	}
	return nil
}

func (m *DisplayInfo) GetRecords() []*RecordInfo {
	if m != nil {
		return m.Records
	}
	return nil
}

type DisplayContent struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Submitter            string   `protobuf:"bytes,2,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Reviewer             string   `protobuf:"bytes,3,opt,name=reviewer,proto3" json:"reviewer,omitempty"`
	Option               uint32   `protobuf:"varint,4,opt,name=option,proto3" json:"option,omitempty"`
	Events               []string `protobuf:"bytes,11,rep,name=events,proto3" json:"events,omitempty"`
	Assets               []string `protobuf:"bytes,12,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisplayContent) Reset()         { *m = DisplayContent{} }
func (m *DisplayContent) String() string { return proto.CompactTextString(m) }
func (*DisplayContent) ProtoMessage()    {}
func (*DisplayContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{1}
}

func (m *DisplayContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisplayContent.Unmarshal(m, b)
}
func (m *DisplayContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisplayContent.Marshal(b, m, deterministic)
}
func (m *DisplayContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisplayContent.Merge(m, src)
}
func (m *DisplayContent) XXX_Size() int {
	return xxx_messageInfo_DisplayContent.Size(m)
}
func (m *DisplayContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DisplayContent.DiscardUnknown(m)
}

var xxx_messageInfo_DisplayContent proto.InternalMessageInfo

func (m *DisplayContent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DisplayContent) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *DisplayContent) GetReviewer() string {
	if m != nil {
		return m.Reviewer
	}
	return ""
}

func (m *DisplayContent) GetOption() uint32 {
	if m != nil {
		return m.Option
	}
	return 0
}

func (m *DisplayContent) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *DisplayContent) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type ReqDisplayAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Origin               string   `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	Status               uint32   `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Keys                 []string `protobuf:"bytes,10,rep,name=keys,proto3" json:"keys,omitempty"`
	Tags                 []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDisplayAdd) Reset()         { *m = ReqDisplayAdd{} }
func (m *ReqDisplayAdd) String() string { return proto.CompactTextString(m) }
func (*ReqDisplayAdd) ProtoMessage()    {}
func (*ReqDisplayAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{2}
}

func (m *ReqDisplayAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDisplayAdd.Unmarshal(m, b)
}
func (m *ReqDisplayAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDisplayAdd.Marshal(b, m, deterministic)
}
func (m *ReqDisplayAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDisplayAdd.Merge(m, src)
}
func (m *ReqDisplayAdd) XXX_Size() int {
	return xxx_messageInfo_ReqDisplayAdd.Size(m)
}
func (m *ReqDisplayAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDisplayAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDisplayAdd proto.InternalMessageInfo

func (m *ReqDisplayAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqDisplayAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqDisplayAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqDisplayAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqDisplayAdd) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqDisplayAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqDisplayAdd) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *ReqDisplayAdd) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqDisplayAdd) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *ReqDisplayAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqDisplayUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Origin               string   `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	Type                 uint32   `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDisplayUpdate) Reset()         { *m = ReqDisplayUpdate{} }
func (m *ReqDisplayUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqDisplayUpdate) ProtoMessage()    {}
func (*ReqDisplayUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{3}
}

func (m *ReqDisplayUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDisplayUpdate.Unmarshal(m, b)
}
func (m *ReqDisplayUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDisplayUpdate.Marshal(b, m, deterministic)
}
func (m *ReqDisplayUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDisplayUpdate.Merge(m, src)
}
func (m *ReqDisplayUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqDisplayUpdate.Size(m)
}
func (m *ReqDisplayUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDisplayUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDisplayUpdate proto.InternalMessageInfo

func (m *ReqDisplayUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqDisplayUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqDisplayUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqDisplayUpdate) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqDisplayUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqDisplayUpdate) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *ReqDisplayUpdate) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReqDisplayTags struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDisplayTags) Reset()         { *m = ReqDisplayTags{} }
func (m *ReqDisplayTags) String() string { return proto.CompactTextString(m) }
func (*ReqDisplayTags) ProtoMessage()    {}
func (*ReqDisplayTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{4}
}

func (m *ReqDisplayTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDisplayTags.Unmarshal(m, b)
}
func (m *ReqDisplayTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDisplayTags.Marshal(b, m, deterministic)
}
func (m *ReqDisplayTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDisplayTags.Merge(m, src)
}
func (m *ReqDisplayTags) XXX_Size() int {
	return xxx_messageInfo_ReqDisplayTags.Size(m)
}
func (m *ReqDisplayTags) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDisplayTags.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDisplayTags proto.InternalMessageInfo

func (m *ReqDisplayTags) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqDisplayTags) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqDisplayTags) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqDisplayList struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDisplayList) Reset()         { *m = ReqDisplayList{} }
func (m *ReqDisplayList) String() string { return proto.CompactTextString(m) }
func (*ReqDisplayList) ProtoMessage()    {}
func (*ReqDisplayList) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{5}
}

func (m *ReqDisplayList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDisplayList.Unmarshal(m, b)
}
func (m *ReqDisplayList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDisplayList.Marshal(b, m, deterministic)
}
func (m *ReqDisplayList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDisplayList.Merge(m, src)
}
func (m *ReqDisplayList) XXX_Size() int {
	return xxx_messageInfo_ReqDisplayList.Size(m)
}
func (m *ReqDisplayList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDisplayList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDisplayList proto.InternalMessageInfo

func (m *ReqDisplayList) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqDisplayList) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReqDisplayMeta struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Meta                 string   `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDisplayMeta) Reset()         { *m = ReqDisplayMeta{} }
func (m *ReqDisplayMeta) String() string { return proto.CompactTextString(m) }
func (*ReqDisplayMeta) ProtoMessage()    {}
func (*ReqDisplayMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{6}
}

func (m *ReqDisplayMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDisplayMeta.Unmarshal(m, b)
}
func (m *ReqDisplayMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDisplayMeta.Marshal(b, m, deterministic)
}
func (m *ReqDisplayMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDisplayMeta.Merge(m, src)
}
func (m *ReqDisplayMeta) XXX_Size() int {
	return xxx_messageInfo_ReqDisplayMeta.Size(m)
}
func (m *ReqDisplayMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDisplayMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDisplayMeta proto.InternalMessageInfo

func (m *ReqDisplayMeta) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqDisplayMeta) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqDisplayMeta) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type ReqDisplayTarget struct {
	Operator             string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Effect               string   `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	Skin                 string   `protobuf:"bytes,4,opt,name=skin,proto3" json:"skin,omitempty"`
	Uid                  string   `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                string   `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Last                 string   `protobuf:"bytes,7,opt,name=last,proto3" json:"last,omitempty"`
	Menu                 string   `protobuf:"bytes,8,opt,name=menu,proto3" json:"menu,omitempty"`
	Slots                []string `protobuf:"bytes,20,rep,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDisplayTarget) Reset()         { *m = ReqDisplayTarget{} }
func (m *ReqDisplayTarget) String() string { return proto.CompactTextString(m) }
func (*ReqDisplayTarget) ProtoMessage()    {}
func (*ReqDisplayTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{7}
}

func (m *ReqDisplayTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDisplayTarget.Unmarshal(m, b)
}
func (m *ReqDisplayTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDisplayTarget.Marshal(b, m, deterministic)
}
func (m *ReqDisplayTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDisplayTarget.Merge(m, src)
}
func (m *ReqDisplayTarget) XXX_Size() int {
	return xxx_messageInfo_ReqDisplayTarget.Size(m)
}
func (m *ReqDisplayTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDisplayTarget.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDisplayTarget proto.InternalMessageInfo

func (m *ReqDisplayTarget) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqDisplayTarget) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ReqDisplayTarget) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *ReqDisplayTarget) GetSkin() string {
	if m != nil {
		return m.Skin
	}
	return ""
}

func (m *ReqDisplayTarget) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqDisplayTarget) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqDisplayTarget) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *ReqDisplayTarget) GetMenu() string {
	if m != nil {
		return m.Menu
	}
	return ""
}

func (m *ReqDisplayTarget) GetSlots() []string {
	if m != nil {
		return m.Slots
	}
	return nil
}

type ReplyDisplayInfo struct {
	Info                 *DisplayInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyDisplayInfo) Reset()         { *m = ReplyDisplayInfo{} }
func (m *ReplyDisplayInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyDisplayInfo) ProtoMessage()    {}
func (*ReplyDisplayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{8}
}

func (m *ReplyDisplayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyDisplayInfo.Unmarshal(m, b)
}
func (m *ReplyDisplayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyDisplayInfo.Marshal(b, m, deterministic)
}
func (m *ReplyDisplayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyDisplayInfo.Merge(m, src)
}
func (m *ReplyDisplayInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyDisplayInfo.Size(m)
}
func (m *ReplyDisplayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyDisplayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyDisplayInfo proto.InternalMessageInfo

func (m *ReplyDisplayInfo) GetInfo() *DisplayInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyDisplayInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyDisplayList struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32         `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32         `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32         `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*DisplayInfo `protobuf:"bytes,20,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyDisplayList) Reset()         { *m = ReplyDisplayList{} }
func (m *ReplyDisplayList) String() string { return proto.CompactTextString(m) }
func (*ReplyDisplayList) ProtoMessage()    {}
func (*ReplyDisplayList) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{9}
}

func (m *ReplyDisplayList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyDisplayList.Unmarshal(m, b)
}
func (m *ReplyDisplayList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyDisplayList.Marshal(b, m, deterministic)
}
func (m *ReplyDisplayList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyDisplayList.Merge(m, src)
}
func (m *ReplyDisplayList) XXX_Size() int {
	return xxx_messageInfo_ReplyDisplayList.Size(m)
}
func (m *ReplyDisplayList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyDisplayList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyDisplayList proto.InternalMessageInfo

func (m *ReplyDisplayList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyDisplayList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyDisplayList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyDisplayList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyDisplayList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyDisplayList) GetList() []*DisplayInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqDisplayContents struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string            `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32            `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Contents             []*DisplayContent `protobuf:"bytes,20,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReqDisplayContents) Reset()         { *m = ReqDisplayContents{} }
func (m *ReqDisplayContents) String() string { return proto.CompactTextString(m) }
func (*ReqDisplayContents) ProtoMessage()    {}
func (*ReqDisplayContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{10}
}

func (m *ReqDisplayContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDisplayContents.Unmarshal(m, b)
}
func (m *ReqDisplayContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDisplayContents.Marshal(b, m, deterministic)
}
func (m *ReqDisplayContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDisplayContents.Merge(m, src)
}
func (m *ReqDisplayContents) XXX_Size() int {
	return xxx_messageInfo_ReqDisplayContents.Size(m)
}
func (m *ReqDisplayContents) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDisplayContents.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDisplayContents proto.InternalMessageInfo

func (m *ReqDisplayContents) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqDisplayContents) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqDisplayContents) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqDisplayContents) GetContents() []*DisplayContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ReplyDisplayContents struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               *ReplyStatus      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Contents             []*DisplayContent `protobuf:"bytes,20,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReplyDisplayContents) Reset()         { *m = ReplyDisplayContents{} }
func (m *ReplyDisplayContents) String() string { return proto.CompactTextString(m) }
func (*ReplyDisplayContents) ProtoMessage()    {}
func (*ReplyDisplayContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_532ca17c360f1227, []int{11}
}

func (m *ReplyDisplayContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyDisplayContents.Unmarshal(m, b)
}
func (m *ReplyDisplayContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyDisplayContents.Marshal(b, m, deterministic)
}
func (m *ReplyDisplayContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyDisplayContents.Merge(m, src)
}
func (m *ReplyDisplayContents) XXX_Size() int {
	return xxx_messageInfo_ReplyDisplayContents.Size(m)
}
func (m *ReplyDisplayContents) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyDisplayContents.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyDisplayContents proto.InternalMessageInfo

func (m *ReplyDisplayContents) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyDisplayContents) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyDisplayContents) GetContents() []*DisplayContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

func init() {
	proto.RegisterType((*DisplayInfo)(nil), "omo.msp.favorite.DisplayInfo")
	proto.RegisterType((*DisplayContent)(nil), "omo.msp.favorite.DisplayContent")
	proto.RegisterType((*ReqDisplayAdd)(nil), "omo.msp.favorite.ReqDisplayAdd")
	proto.RegisterType((*ReqDisplayUpdate)(nil), "omo.msp.favorite.ReqDisplayUpdate")
	proto.RegisterType((*ReqDisplayTags)(nil), "omo.msp.favorite.ReqDisplayTags")
	proto.RegisterType((*ReqDisplayList)(nil), "omo.msp.favorite.ReqDisplayList")
	proto.RegisterType((*ReqDisplayMeta)(nil), "omo.msp.favorite.ReqDisplayMeta")
	proto.RegisterType((*ReqDisplayTarget)(nil), "omo.msp.favorite.ReqDisplayTarget")
	proto.RegisterType((*ReplyDisplayInfo)(nil), "omo.msp.favorite.ReplyDisplayInfo")
	proto.RegisterType((*ReplyDisplayList)(nil), "omo.msp.favorite.ReplyDisplayList")
	proto.RegisterType((*ReqDisplayContents)(nil), "omo.msp.favorite.ReqDisplayContents")
	proto.RegisterType((*ReplyDisplayContents)(nil), "omo.msp.favorite.ReplyDisplayContents")
}

func init() {
	proto.RegisterFile("proto/favorite/display.proto", fileDescriptor_532ca17c360f1227)
}

var fileDescriptor_532ca17c360f1227 = []byte{
	// 1083 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0xf3, 0xdb, 0x4c, 0x9a, 0x6c, 0x18, 0x55, 0x68, 0x94, 0x2d, 0x5b, 0xcb, 0x42, 0x28,
	0xdc, 0x64, 0x45, 0x11, 0x5c, 0xac, 0xb8, 0xe9, 0x2e, 0xa2, 0x5a, 0x89, 0x55, 0xc1, 0x2d, 0x08,
	0xed, 0x15, 0x8e, 0x3d, 0x89, 0xac, 0xc6, 0x1e, 0xaf, 0x67, 0x92, 0x55, 0x24, 0x1e, 0x83, 0x5b,
	0xee, 0xb8, 0xe6, 0x69, 0x90, 0xe0, 0x82, 0x77, 0xe0, 0x15, 0xd0, 0x39, 0x33, 0x13, 0x3b, 0x6d,
	0x7e, 0xd9, 0xbd, 0x9b, 0xef, 0xf8, 0xcc, 0x37, 0xe7, 0xe7, 0x9b, 0x33, 0x09, 0x39, 0xcb, 0x72,
	0xa1, 0xc4, 0xd3, 0x71, 0x30, 0x17, 0x79, 0xac, 0xf8, 0xd3, 0x28, 0x96, 0xd9, 0x34, 0x58, 0x0c,
	0xd1, 0x4c, 0x7b, 0x22, 0x11, 0xc3, 0x44, 0x66, 0x43, 0xfb, 0xbd, 0xff, 0xf8, 0x9e, 0x7f, 0x28,
	0x92, 0x44, 0xa4, 0xda, 0xdd, 0xfb, 0xab, 0x46, 0xda, 0x5f, 0x6b, 0x82, 0x97, 0xe9, 0x58, 0xd0,
	0x1e, 0xa9, 0xce, 0xe2, 0x88, 0x39, 0xae, 0x33, 0x68, 0xf9, 0xb0, 0xa4, 0x5d, 0x52, 0x89, 0x23,
	0x56, 0x71, 0x9d, 0x41, 0xcd, 0xaf, 0xc4, 0x11, 0x65, 0xa4, 0x19, 0xe6, 0x3c, 0x50, 0x3c, 0x62,
	0x55, 0xd7, 0x19, 0x54, 0x7d, 0x0b, 0xe1, 0xcb, 0x2c, 0x8b, 0xf0, 0x4b, 0x4d, 0x7f, 0x31, 0x90,
	0x52, 0x52, 0x4b, 0x83, 0x84, 0xb3, 0x3a, 0xd2, 0xe2, 0x9a, 0x9e, 0x92, 0xba, 0x78, 0x9b, 0xf2,
	0x9c, 0x35, 0xd0, 0xa8, 0x01, 0xfd, 0x90, 0x34, 0x72, 0x9e, 0x04, 0xf9, 0x1d, 0x6b, 0xa2, 0xd9,
	0xa0, 0xe5, 0xa9, 0x22, 0x67, 0xc7, 0xf8, 0xc1, 0x42, 0xda, 0x27, 0xc7, 0x22, 0xe3, 0x39, 0x7e,
	0x6a, 0xe1, 0xa7, 0x25, 0x86, 0x33, 0x42, 0x31, 0xe7, 0x39, 0x23, 0xfa, 0x0c, 0x04, 0x70, 0x86,
	0xc8, 0xe3, 0x49, 0x9c, 0xb2, 0xb6, 0x3e, 0x43, 0x23, 0x88, 0x52, 0x2d, 0x32, 0xce, 0x4e, 0x5c,
	0x67, 0xd0, 0xf1, 0x71, 0x0d, 0xb6, 0x84, 0xab, 0x80, 0x75, 0x74, 0xe4, 0xb0, 0x86, 0xfd, 0x52,
	0x05, 0x6a, 0x26, 0x59, 0x17, 0x3d, 0x0d, 0x02, 0xfb, 0x28, 0x48, 0x21, 0xa5, 0x47, 0x9a, 0x57,
	0x23, 0xb0, 0x67, 0x42, 0x2a, 0x9e, 0xb3, 0x9e, 0xb6, 0x6b, 0x04, 0xf6, 0x20, 0x0c, 0xb9, 0x94,
	0xec, 0x03, 0xcd, 0xa3, 0x11, 0xc6, 0x11, 0x4c, 0x24, 0x7b, 0xe2, 0x56, 0xe1, 0x4c, 0x58, 0xd3,
	0xaf, 0xc8, 0x71, 0x28, 0x52, 0xc5, 0x53, 0x25, 0xd9, 0xb9, 0x5b, 0x1d, 0xb4, 0x2f, 0xdc, 0xe1,
	0xfd, 0x4e, 0x0f, 0x4d, 0x23, 0x5f, 0x68, 0x47, 0x7f, 0xb9, 0x83, 0x3e, 0x23, 0xcd, 0x8c, 0xa7,
	0x51, 0x9c, 0x4e, 0x98, 0xbb, 0xe7, 0x66, 0xbb, 0x81, 0x7e, 0x49, 0x9a, 0x39, 0x0f, 0x45, 0x1e,
	0x49, 0xf6, 0x29, 0xee, 0x3d, 0x7b, 0xb8, 0xd7, 0x47, 0x07, 0x10, 0x90, 0x6f, 0x9d, 0xbd, 0xdf,
	0x1d, 0xd2, 0x5d, 0xe5, 0x5c, 0x23, 0xae, 0x33, 0xd2, 0x92, 0xb3, 0x51, 0x12, 0x2b, 0xa8, 0x4e,
	0x05, 0xed, 0x85, 0x01, 0x5a, 0x9b, 0xf3, 0x79, 0xcc, 0xdf, 0xf2, 0x1c, 0xb5, 0xd6, 0xf2, 0x97,
	0x18, 0x9b, 0x98, 0xa9, 0x58, 0xa4, 0xa8, 0xb5, 0x8e, 0x6f, 0x10, 0xd8, 0xf9, 0x1c, 0xcb, 0xd4,
	0xc6, 0xf2, 0x19, 0x84, 0xc5, 0x96, 0x92, 0x2b, 0xc9, 0x4e, 0xb4, 0x5d, 0x23, 0xef, 0x5f, 0x87,
	0x74, 0x7c, 0xfe, 0xc6, 0x44, 0x7a, 0x19, 0x15, 0x62, 0x75, 0xd6, 0x89, 0xb5, 0xb2, 0x5e, 0xac,
	0xd5, 0x15, 0xb1, 0x2e, 0x65, 0x57, 0x2b, 0xcb, 0xce, 0xca, 0x0b, 0x2e, 0x41, 0xdd, 0xc8, 0xab,
	0x2c, 0xde, 0xc6, 0x3d, 0xf1, 0x16, 0x32, 0x6d, 0xae, 0xc8, 0xb4, 0x90, 0x5f, 0x6b, 0x45, 0x7e,
	0x94, 0xd4, 0xee, 0xf8, 0x42, 0x32, 0xa2, 0x65, 0x03, 0xeb, 0xa5, 0x94, 0xda, 0x85, 0x94, 0xbc,
	0x3f, 0x1c, 0xd2, 0x2b, 0x32, 0xfe, 0x01, 0xaf, 0xe8, 0x9a, 0xd6, 0xd8, 0x32, 0x54, 0x4a, 0x65,
	0x38, 0x2c, 0xe1, 0x72, 0x72, 0xf5, 0x8d, 0xc9, 0x35, 0xd6, 0xde, 0xc1, 0x66, 0x71, 0x07, 0x3d,
	0x9f, 0x74, 0x8b, 0x78, 0x6f, 0xe1, 0x36, 0x3c, 0x8c, 0xb6, 0x7c, 0x56, 0xe5, 0xde, 0x59, 0xb6,
	0x08, 0xd5, 0x52, 0x11, 0x9e, 0x95, 0x39, 0xbf, 0x8d, 0xa5, 0x2a, 0x5a, 0xec, 0x94, 0x5b, 0x6c,
	0xe3, 0xa9, 0x6c, 0x8a, 0xe7, 0x15, 0x4c, 0x84, 0x83, 0xe3, 0xc1, 0x99, 0x52, 0x2b, 0x66, 0x8a,
	0xf7, 0xf7, 0x4a, 0x53, 0x6e, 0x83, 0x7c, 0xc2, 0xd5, 0x0a, 0x89, 0xf3, 0xb0, 0x80, 0x0a, 0xbd,
	0x0c, 0xbd, 0x41, 0xa8, 0xff, 0xf1, 0x98, 0x87, 0xca, 0xb6, 0x48, 0x23, 0x38, 0x54, 0xde, 0xc5,
	0xa9, 0x3d, 0x14, 0xd6, 0x36, 0xec, 0x7a, 0x11, 0xf6, 0xfa, 0xa1, 0x4c, 0x49, 0x6d, 0x1a, 0x48,
	0x65, 0x74, 0x88, 0x6b, 0x9d, 0x44, 0x3a, 0x33, 0xd3, 0x18, 0xd7, 0xb0, 0x5b, 0x4e, 0x85, 0x92,
	0xec, 0x14, 0x2b, 0xad, 0x81, 0xf7, 0x0b, 0x64, 0x96, 0x4d, 0x17, 0xe5, 0x67, 0xe6, 0x33, 0x52,
	0x8b, 0xd3, 0xb1, 0xc0, 0xac, 0xda, 0x17, 0x1f, 0x6d, 0x9c, 0x46, 0x38, 0x52, 0xd0, 0x95, 0x7e,
	0xb1, 0x94, 0x7d, 0x65, 0xd3, 0x26, 0x3c, 0xe6, 0x06, 0x9d, 0xec, 0xad, 0xf0, 0xfe, 0x74, 0x56,
	0x8f, 0xc7, 0x5e, 0x17, 0x5c, 0xce, 0x01, 0x5c, 0x90, 0x9f, 0x12, 0x2a, 0x98, 0x1a, 0x35, 0x68,
	0x00, 0xd6, 0x2c, 0x98, 0x70, 0x89, 0x05, 0xef, 0xf8, 0x1a, 0x40, 0x7d, 0x60, 0x61, 0xa6, 0x13,
	0xae, 0xa1, 0x37, 0xe9, 0x2c, 0x19, 0x71, 0x7d, 0x1d, 0x3a, 0xbe, 0x41, 0x50, 0x8d, 0x69, 0x2c,
	0x15, 0x96, 0x6d, 0x77, 0x35, 0xc0, 0xd5, 0xfb, 0xd5, 0x21, 0xb4, 0xd0, 0xcb, 0x0b, 0x3b, 0xe8,
	0x0f, 0xbf, 0x18, 0x20, 0xee, 0x6a, 0xe9, 0xc1, 0x2b, 0x3f, 0x34, 0xa7, 0x87, 0x3e, 0x34, 0xde,
	0x6f, 0x0e, 0x39, 0x2d, 0x57, 0x7b, 0x4b, 0x60, 0xff, 0xaf, 0x9f, 0xef, 0x16, 0xdf, 0xc5, 0x3f,
	0x64, 0xf9, 0x28, 0xdd, 0xf0, 0x7c, 0x1e, 0x87, 0x9c, 0x5e, 0x93, 0xc6, 0x65, 0x14, 0x5d, 0xa7,
	0x9c, 0x9e, 0xaf, 0x8b, 0xa0, 0xf4, 0x32, 0xf4, 0xbd, 0x0d, 0x21, 0x96, 0xda, 0xe3, 0x1d, 0xd1,
	0x57, 0xa4, 0x71, 0xc5, 0x15, 0x10, 0xae, 0x4d, 0xe9, 0xcd, 0x8c, 0x4b, 0x05, 0xae, 0x7b, 0xd2,
	0xf9, 0xa4, 0x7d, 0xc5, 0xd5, 0xf3, 0xc5, 0xb5, 0x1e, 0x90, 0xef, 0x85, 0xf3, 0x7b, 0xd2, 0xbc,
	0xe2, 0x0a, 0xaf, 0x82, 0xbb, 0x2d, 0x69, 0xf0, 0xd8, 0x45, 0x09, 0x3e, 0xde, 0x11, 0xfd, 0x8e,
	0xb4, 0x30, 0x4c, 0x24, 0xdd, 0x1c, 0xe4, 0x01, 0x8c, 0xb7, 0x26, 0xf1, 0x6f, 0xe2, 0x29, 0xfc,
	0x18, 0x38, 0xdf, 0xc8, 0xa9, 0x1d, 0xf6, 0x64, 0xbd, 0x21, 0x27, 0x57, 0x5c, 0x81, 0xa8, 0x62,
	0xa9, 0xe2, 0x70, 0x37, 0xad, 0xbb, 0x45, 0x97, 0x48, 0x81, 0xc9, 0x77, 0xf5, 0x3b, 0xba, 0x47,
	0xb4, 0xda, 0xb1, 0xff, 0x78, 0x03, 0xad, 0xe9, 0xd0, 0x8f, 0x84, 0x18, 0xc6, 0x40, 0x72, 0xea,
	0x6d, 0x6b, 0x92, 0x21, 0xdc, 0xaf, 0xf3, 0xb7, 0x96, 0x17, 0xdf, 0xad, 0xad, 0xcd, 0x07, 0x8f,
	0x43, 0x59, 0xf1, 0x75, 0xde, 0xca, 0x0a, 0x1e, 0x7b, 0x5f, 0xa4, 0x13, 0xcd, 0xaa, 0x47, 0x00,
	0x7d, 0xb2, 0xb1, 0xa6, 0xe0, 0xb0, 0xb3, 0xa4, 0x2f, 0x49, 0xcb, 0xe7, 0x89, 0x98, 0xf3, 0x3d,
	0xae, 0xe6, 0x0e, 0xaa, 0x9f, 0x6d, 0xbf, 0x97, 0xf3, 0xed, 0xe3, 0x6d, 0x39, 0x5b, 0xaf, 0xfe,
	0x27, 0xdb, 0xf3, 0xb6, 0x7e, 0xde, 0x11, 0xfd, 0x89, 0x74, 0x2e, 0x33, 0xf8, 0x09, 0x6e, 0x7f,
	0x3b, 0xef, 0x08, 0x78, 0x7f, 0xe6, 0xd7, 0xe4, 0xd1, 0xcd, 0x6c, 0xa4, 0xf2, 0x20, 0x54, 0xef,
	0x9b, 0xfb, 0x79, 0xef, 0x75, 0x77, 0xf5, 0xcf, 0xe6, 0xa8, 0x81, 0xf8, 0xf3, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x81, 0xee, 0xd3, 0xac, 0xb5, 0x0e, 0x00, 0x00,
}
