// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/favorite/notice.proto

package favorite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoticeInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Body                 string   `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	Subtitle             string   `protobuf:"bytes,10,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Owner                string   `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	Status               uint32   `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Targets              []string `protobuf:"bytes,13,rep,name=targets,proto3" json:"targets,omitempty"`
	Tags                 []string `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeInfo) Reset()         { *m = NoticeInfo{} }
func (m *NoticeInfo) String() string { return proto.CompactTextString(m) }
func (*NoticeInfo) ProtoMessage()    {}
func (*NoticeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_949156a11f363448, []int{0}
}

func (m *NoticeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeInfo.Unmarshal(m, b)
}
func (m *NoticeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeInfo.Marshal(b, m, deterministic)
}
func (m *NoticeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeInfo.Merge(m, src)
}
func (m *NoticeInfo) XXX_Size() int {
	return xxx_messageInfo_NoticeInfo.Size(m)
}
func (m *NoticeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeInfo proto.InternalMessageInfo

func (m *NoticeInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *NoticeInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NoticeInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *NoticeInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *NoticeInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *NoticeInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *NoticeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NoticeInfo) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *NoticeInfo) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *NoticeInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NoticeInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NoticeInfo) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *NoticeInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqNoticeAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle             string   `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Targets              []string `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNoticeAdd) Reset()         { *m = ReqNoticeAdd{} }
func (m *ReqNoticeAdd) String() string { return proto.CompactTextString(m) }
func (*ReqNoticeAdd) ProtoMessage()    {}
func (*ReqNoticeAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_949156a11f363448, []int{1}
}

func (m *ReqNoticeAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNoticeAdd.Unmarshal(m, b)
}
func (m *ReqNoticeAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNoticeAdd.Marshal(b, m, deterministic)
}
func (m *ReqNoticeAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNoticeAdd.Merge(m, src)
}
func (m *ReqNoticeAdd) XXX_Size() int {
	return xxx_messageInfo_ReqNoticeAdd.Size(m)
}
func (m *ReqNoticeAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNoticeAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNoticeAdd proto.InternalMessageInfo

func (m *ReqNoticeAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqNoticeAdd) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *ReqNoticeAdd) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ReqNoticeAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqNoticeAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqNoticeAdd) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type ReqNoticeUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle             string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Targets              []string `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNoticeUpdate) Reset()         { *m = ReqNoticeUpdate{} }
func (m *ReqNoticeUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqNoticeUpdate) ProtoMessage()    {}
func (*ReqNoticeUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_949156a11f363448, []int{2}
}

func (m *ReqNoticeUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNoticeUpdate.Unmarshal(m, b)
}
func (m *ReqNoticeUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNoticeUpdate.Marshal(b, m, deterministic)
}
func (m *ReqNoticeUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNoticeUpdate.Merge(m, src)
}
func (m *ReqNoticeUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqNoticeUpdate.Size(m)
}
func (m *ReqNoticeUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNoticeUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNoticeUpdate proto.InternalMessageInfo

func (m *ReqNoticeUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqNoticeUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqNoticeUpdate) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *ReqNoticeUpdate) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ReqNoticeUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqNoticeUpdate) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type ReqNoticeState struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNoticeState) Reset()         { *m = ReqNoticeState{} }
func (m *ReqNoticeState) String() string { return proto.CompactTextString(m) }
func (*ReqNoticeState) ProtoMessage()    {}
func (*ReqNoticeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_949156a11f363448, []int{3}
}

func (m *ReqNoticeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNoticeState.Unmarshal(m, b)
}
func (m *ReqNoticeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNoticeState.Marshal(b, m, deterministic)
}
func (m *ReqNoticeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNoticeState.Merge(m, src)
}
func (m *ReqNoticeState) XXX_Size() int {
	return xxx_messageInfo_ReqNoticeState.Size(m)
}
func (m *ReqNoticeState) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNoticeState.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNoticeState proto.InternalMessageInfo

func (m *ReqNoticeState) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqNoticeState) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqNoticeState) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyNoticeInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *NoticeInfo  `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyNoticeInfo) Reset()         { *m = ReplyNoticeInfo{} }
func (m *ReplyNoticeInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyNoticeInfo) ProtoMessage()    {}
func (*ReplyNoticeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_949156a11f363448, []int{4}
}

func (m *ReplyNoticeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyNoticeInfo.Unmarshal(m, b)
}
func (m *ReplyNoticeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyNoticeInfo.Marshal(b, m, deterministic)
}
func (m *ReplyNoticeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyNoticeInfo.Merge(m, src)
}
func (m *ReplyNoticeInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyNoticeInfo.Size(m)
}
func (m *ReplyNoticeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyNoticeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyNoticeInfo proto.InternalMessageInfo

func (m *ReplyNoticeInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyNoticeInfo) GetInfo() *NoticeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyNoticeList struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*NoticeInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyNoticeList) Reset()         { *m = ReplyNoticeList{} }
func (m *ReplyNoticeList) String() string { return proto.CompactTextString(m) }
func (*ReplyNoticeList) ProtoMessage()    {}
func (*ReplyNoticeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_949156a11f363448, []int{5}
}

func (m *ReplyNoticeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyNoticeList.Unmarshal(m, b)
}
func (m *ReplyNoticeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyNoticeList.Marshal(b, m, deterministic)
}
func (m *ReplyNoticeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyNoticeList.Merge(m, src)
}
func (m *ReplyNoticeList) XXX_Size() int {
	return xxx_messageInfo_ReplyNoticeList.Size(m)
}
func (m *ReplyNoticeList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyNoticeList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyNoticeList proto.InternalMessageInfo

func (m *ReplyNoticeList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyNoticeList) GetList() []*NoticeInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*NoticeInfo)(nil), "omo.msp.favorite.NoticeInfo")
	proto.RegisterType((*ReqNoticeAdd)(nil), "omo.msp.favorite.ReqNoticeAdd")
	proto.RegisterType((*ReqNoticeUpdate)(nil), "omo.msp.favorite.ReqNoticeUpdate")
	proto.RegisterType((*ReqNoticeState)(nil), "omo.msp.favorite.ReqNoticeState")
	proto.RegisterType((*ReplyNoticeInfo)(nil), "omo.msp.favorite.ReplyNoticeInfo")
	proto.RegisterType((*ReplyNoticeList)(nil), "omo.msp.favorite.ReplyNoticeList")
}

func init() {
	proto.RegisterFile("proto/favorite/notice.proto", fileDescriptor_949156a11f363448)
}

var fileDescriptor_949156a11f363448 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x97, 0x8f, 0xa6, 0xdb, 0xe9, 0x07, 0x95, 0x85, 0x90, 0xd5, 0xf1, 0x91, 0xe5, 0xaa,
	0x57, 0x1d, 0x2a, 0xe2, 0x01, 0xb6, 0x0b, 0x26, 0xd0, 0xc6, 0xa4, 0x6c, 0x70, 0xc1, 0x5d, 0x5a,
	0xbb, 0x95, 0xa5, 0x36, 0xee, 0x62, 0x67, 0x68, 0xbc, 0x0b, 0x3c, 0x07, 0x77, 0xbc, 0x1a, 0xb2,
	0x9d, 0xa4, 0x49, 0x68, 0xda, 0x89, 0xdd, 0xf9, 0xf8, 0x1c, 0xff, 0xff, 0x3f, 0x9f, 0xe3, 0x36,
	0x70, 0xbc, 0x4e, 0xb8, 0xe4, 0xa7, 0xf3, 0xe8, 0x9e, 0x27, 0x4c, 0xd2, 0xd3, 0x98, 0x4b, 0x36,
	0xa3, 0x63, 0xbd, 0x8b, 0x06, 0x7c, 0xc5, 0xc7, 0x2b, 0xb1, 0x1e, 0xe7, 0xe9, 0x61, 0xbd, 0x7c,
	0xc6, 0x57, 0x2b, 0x1e, 0x9b, 0xf2, 0xe0, 0xb7, 0x0d, 0xf0, 0x59, 0x9f, 0xff, 0x18, 0xcf, 0x39,
	0x1a, 0x80, 0x93, 0x32, 0x82, 0x2d, 0xdf, 0x1a, 0x1d, 0x85, 0x6a, 0x89, 0xfa, 0x60, 0x33, 0x82,
	0x6d, 0xdf, 0x1a, 0xb9, 0xa1, 0xcd, 0x08, 0xc2, 0xd0, 0x9e, 0x25, 0x34, 0x92, 0x94, 0x60, 0xd7,
	0xb7, 0x46, 0x4e, 0x98, 0x87, 0x2a, 0x93, 0xae, 0x89, 0xce, 0xb4, 0x4c, 0x26, 0x0b, 0x8b, 0x33,
	0x3c, 0xc1, 0x9e, 0x56, 0xce, 0x43, 0x34, 0x84, 0x43, 0xbe, 0xa6, 0x89, 0x4e, 0xb5, 0x75, 0xaa,
	0x88, 0x11, 0x02, 0x37, 0x8e, 0x56, 0x14, 0x1f, 0xea, 0x7d, 0xbd, 0x56, 0x7b, 0x53, 0x4e, 0x1e,
	0xf0, 0x91, 0xd9, 0x53, 0x6b, 0xa5, 0x21, 0xd2, 0xa9, 0x64, 0x72, 0x49, 0x31, 0x18, 0x8d, 0x3c,
	0x46, 0xcf, 0xa1, 0xc5, 0xbf, 0xc7, 0x34, 0xc1, 0x1d, 0x9d, 0x30, 0x01, 0x7a, 0x01, 0x9e, 0x90,
	0x91, 0x4c, 0x05, 0xee, 0xfa, 0xd6, 0xa8, 0x17, 0x66, 0x91, 0xe2, 0x94, 0x51, 0xb2, 0xa0, 0x52,
	0xe0, 0x9e, 0xef, 0x28, 0xce, 0x2c, 0x54, 0xbe, 0x32, 0x5a, 0x08, 0xdc, 0xd7, 0xdb, 0x7a, 0x1d,
	0xfc, 0xb2, 0xa0, 0x1b, 0xd2, 0x3b, 0xd3, 0xbd, 0x33, 0x42, 0x0a, 0x60, 0xab, 0x04, 0x5c, 0x86,
	0xb3, 0x6b, 0x70, 0xf9, 0x65, 0x9c, 0xd2, 0x65, 0x0a, 0x60, 0xb7, 0x0c, 0x5c, 0x6e, 0x53, 0xab,
	0xd6, 0xa6, 0x12, 0xb4, 0x57, 0x81, 0x0e, 0x7e, 0x5a, 0xf0, 0xac, 0x00, 0xfc, 0xa2, 0x67, 0xb1,
	0x65, 0xc0, 0x39, 0xb5, 0xdd, 0x40, 0xed, 0x34, 0x50, 0xbb, 0xd5, 0x11, 0xfc, 0x07, 0xdf, 0x57,
	0xe8, 0x17, 0x78, 0x37, 0x72, 0x3b, 0xdd, 0x66, 0x54, 0x76, 0x65, 0x54, 0x65, 0x47, 0xa7, 0xea,
	0x18, 0xfc, 0x50, 0xd7, 0x5e, 0x2f, 0x1f, 0x4a, 0xef, 0xfa, 0x7d, 0x21, 0xa3, 0xb4, 0x3b, 0x93,
	0x57, 0xe3, 0xfa, 0xcf, 0x64, 0xac, 0x8f, 0xdc, 0xe8, 0xa2, 0xc2, 0xe5, 0x2d, 0xb8, 0x2c, 0x9e,
	0x73, 0xed, 0xdd, 0x99, 0xbc, 0xfc, 0xf7, 0xd0, 0xc6, 0x22, 0xd4, 0x95, 0x35, 0xef, 0x4b, 0x26,
	0xe4, 0x13, 0xbc, 0x97, 0x4c, 0x48, 0x6c, 0xfb, 0xce, 0x7e, 0x6f, 0x55, 0x39, 0xf9, 0xe3, 0x42,
	0x2f, 0xeb, 0x26, 0x4d, 0xee, 0xd9, 0x8c, 0xa2, 0x2b, 0xf0, 0xce, 0x08, 0xb9, 0x8e, 0x29, 0x7a,
	0xbd, 0xcd, 0x74, 0xf3, 0x76, 0x87, 0x27, 0x0d, 0x50, 0x1b, 0x93, 0xe0, 0x00, 0x5d, 0x82, 0x77,
	0x41, 0xa5, 0x92, 0xdb, 0x7a, 0x87, 0xbb, 0x94, 0x0a, 0xa9, 0x4a, 0x1f, 0xa7, 0x76, 0x0d, 0xed,
	0x0b, 0x2a, 0x75, 0x8b, 0xde, 0x34, 0xca, 0x7d, 0x60, 0x4b, 0x49, 0x93, 0x3d, 0x82, 0x4a, 0x23,
	0x38, 0x40, 0xb7, 0x00, 0xe6, 0x95, 0x9f, 0x47, 0x82, 0xa2, 0x93, 0x1d, 0x37, 0x36, 0x65, 0x8f,
	0xc5, 0xec, 0x9a, 0x72, 0x33, 0x1f, 0xe4, 0xef, 0xd0, 0xd5, 0xaf, 0x78, 0x78, 0xdc, 0x20, 0x9b,
	0x09, 0x7e, 0xca, 0x31, 0x6f, 0xa3, 0x85, 0xd8, 0xd1, 0x49, 0x75, 0xab, 0x7d, 0x5a, 0x57, 0xd0,
	0xcb, 0xb5, 0xcc, 0x1f, 0xd5, 0x93, 0xe4, 0xce, 0x07, 0xdf, 0xfa, 0xd5, 0x8f, 0xc5, 0xd4, 0xd3,
	0xf1, 0xbb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x14, 0x76, 0x1b, 0x42, 0x74, 0x06, 0x00, 0x00,
}
