// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/favorite/product.proto

package favorite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductInfo struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32           `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64            `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64            `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string           `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string           `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string           `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Menus                string           `protobuf:"bytes,9,opt,name=menus,proto3" json:"menus,omitempty"`
	Key                  string           `protobuf:"bytes,11,opt,name=key,proto3" json:"key,omitempty"`
	Templet              string           `protobuf:"bytes,12,opt,name=templet,proto3" json:"templet,omitempty"`
	Catalogs             string           `protobuf:"bytes,13,opt,name=catalogs,proto3" json:"catalogs,omitempty"`
	Status               uint32           `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	Remark               string           `protobuf:"bytes,15,opt,name=remark,proto3" json:"remark,omitempty"`
	Limit                uint32           `protobuf:"varint,16,opt,name=limit,proto3" json:"limit,omitempty"`
	Entries              []string         `protobuf:"bytes,30,rep,name=entries,proto3" json:"entries,omitempty"`
	Revises              []string         `protobuf:"bytes,31,rep,name=revises,proto3" json:"revises,omitempty"`
	Shows                []string         `protobuf:"bytes,32,rep,name=shows,proto3" json:"shows,omitempty"`
	Effects              []*ProductEffect `protobuf:"bytes,41,rep,name=effects,proto3" json:"effects,omitempty"`
	Displays             []*DisplayShow   `protobuf:"bytes,42,rep,name=displays,proto3" json:"displays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProductInfo) Reset()         { *m = ProductInfo{} }
func (m *ProductInfo) String() string { return proto.CompactTextString(m) }
func (*ProductInfo) ProtoMessage()    {}
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{0}
}

func (m *ProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductInfo.Unmarshal(m, b)
}
func (m *ProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductInfo.Marshal(b, m, deterministic)
}
func (m *ProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductInfo.Merge(m, src)
}
func (m *ProductInfo) XXX_Size() int {
	return xxx_messageInfo_ProductInfo.Size(m)
}
func (m *ProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProductInfo proto.InternalMessageInfo

func (m *ProductInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ProductInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ProductInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ProductInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ProductInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ProductInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ProductInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductInfo) GetMenus() string {
	if m != nil {
		return m.Menus
	}
	return ""
}

func (m *ProductInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ProductInfo) GetTemplet() string {
	if m != nil {
		return m.Templet
	}
	return ""
}

func (m *ProductInfo) GetCatalogs() string {
	if m != nil {
		return m.Catalogs
	}
	return ""
}

func (m *ProductInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ProductInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ProductInfo) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ProductInfo) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *ProductInfo) GetRevises() []string {
	if m != nil {
		return m.Revises
	}
	return nil
}

func (m *ProductInfo) GetShows() []string {
	if m != nil {
		return m.Shows
	}
	return nil
}

func (m *ProductInfo) GetEffects() []*ProductEffect {
	if m != nil {
		return m.Effects
	}
	return nil
}

func (m *ProductInfo) GetDisplays() []*DisplayShow {
	if m != nil {
		return m.Displays
	}
	return nil
}

type ProductEffect struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Min                  uint32   `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  uint32   `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Access               uint32   `protobuf:"varint,4,opt,name=access,proto3" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductEffect) Reset()         { *m = ProductEffect{} }
func (m *ProductEffect) String() string { return proto.CompactTextString(m) }
func (*ProductEffect) ProtoMessage()    {}
func (*ProductEffect) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{1}
}

func (m *ProductEffect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductEffect.Unmarshal(m, b)
}
func (m *ProductEffect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductEffect.Marshal(b, m, deterministic)
}
func (m *ProductEffect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductEffect.Merge(m, src)
}
func (m *ProductEffect) XXX_Size() int {
	return xxx_messageInfo_ProductEffect.Size(m)
}
func (m *ProductEffect) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductEffect.DiscardUnknown(m)
}

var xxx_messageInfo_ProductEffect proto.InternalMessageInfo

func (m *ProductEffect) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *ProductEffect) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *ProductEffect) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *ProductEffect) GetAccess() uint32 {
	if m != nil {
		return m.Access
	}
	return 0
}

type DisplayShow struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Effect               string   `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisplayShow) Reset()         { *m = DisplayShow{} }
func (m *DisplayShow) String() string { return proto.CompactTextString(m) }
func (*DisplayShow) ProtoMessage()    {}
func (*DisplayShow) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{2}
}

func (m *DisplayShow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisplayShow.Unmarshal(m, b)
}
func (m *DisplayShow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisplayShow.Marshal(b, m, deterministic)
}
func (m *DisplayShow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisplayShow.Merge(m, src)
}
func (m *DisplayShow) XXX_Size() int {
	return xxx_messageInfo_DisplayShow.Size(m)
}
func (m *DisplayShow) XXX_DiscardUnknown() {
	xxx_messageInfo_DisplayShow.DiscardUnknown(m)
}

var xxx_messageInfo_DisplayShow proto.InternalMessageInfo

func (m *DisplayShow) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DisplayShow) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

type ReqProductAdd struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string           `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Menus                string           `protobuf:"bytes,4,opt,name=menus,proto3" json:"menus,omitempty"`
	Operator             string           `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32           `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Templet              string           `protobuf:"bytes,7,opt,name=templet,proto3" json:"templet,omitempty"`
	Remark               string           `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Entries              []string         `protobuf:"bytes,16,rep,name=entries,proto3" json:"entries,omitempty"`
	Revises              []string         `protobuf:"bytes,17,rep,name=revises,proto3" json:"revises,omitempty"`
	Shows                []string         `protobuf:"bytes,18,rep,name=shows,proto3" json:"shows,omitempty"`
	Effects              []*ProductEffect `protobuf:"bytes,31,rep,name=effects,proto3" json:"effects,omitempty"`
	Displays             []*DisplayShow   `protobuf:"bytes,32,rep,name=displays,proto3" json:"displays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqProductAdd) Reset()         { *m = ReqProductAdd{} }
func (m *ReqProductAdd) String() string { return proto.CompactTextString(m) }
func (*ReqProductAdd) ProtoMessage()    {}
func (*ReqProductAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{3}
}

func (m *ReqProductAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProductAdd.Unmarshal(m, b)
}
func (m *ReqProductAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProductAdd.Marshal(b, m, deterministic)
}
func (m *ReqProductAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProductAdd.Merge(m, src)
}
func (m *ReqProductAdd) XXX_Size() int {
	return xxx_messageInfo_ReqProductAdd.Size(m)
}
func (m *ReqProductAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProductAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProductAdd proto.InternalMessageInfo

func (m *ReqProductAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqProductAdd) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqProductAdd) GetMenus() string {
	if m != nil {
		return m.Menus
	}
	return ""
}

func (m *ReqProductAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqProductAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqProductAdd) GetTemplet() string {
	if m != nil {
		return m.Templet
	}
	return ""
}

func (m *ReqProductAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqProductAdd) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *ReqProductAdd) GetRevises() []string {
	if m != nil {
		return m.Revises
	}
	return nil
}

func (m *ReqProductAdd) GetShows() []string {
	if m != nil {
		return m.Shows
	}
	return nil
}

func (m *ReqProductAdd) GetEffects() []*ProductEffect {
	if m != nil {
		return m.Effects
	}
	return nil
}

func (m *ReqProductAdd) GetDisplays() []*DisplayShow {
	if m != nil {
		return m.Displays
	}
	return nil
}

type ReqProductUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqProductUpdate) Reset()         { *m = ReqProductUpdate{} }
func (m *ReqProductUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqProductUpdate) ProtoMessage()    {}
func (*ReqProductUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{4}
}

func (m *ReqProductUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProductUpdate.Unmarshal(m, b)
}
func (m *ReqProductUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProductUpdate.Marshal(b, m, deterministic)
}
func (m *ReqProductUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProductUpdate.Merge(m, src)
}
func (m *ReqProductUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqProductUpdate.Size(m)
}
func (m *ReqProductUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProductUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProductUpdate proto.InternalMessageInfo

func (m *ReqProductUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqProductUpdate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqProductUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqProductUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqProductUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqProductDisplay struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Display              string   `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Effect               string   `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqProductDisplay) Reset()         { *m = ReqProductDisplay{} }
func (m *ReqProductDisplay) String() string { return proto.CompactTextString(m) }
func (*ReqProductDisplay) ProtoMessage()    {}
func (*ReqProductDisplay) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{5}
}

func (m *ReqProductDisplay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProductDisplay.Unmarshal(m, b)
}
func (m *ReqProductDisplay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProductDisplay.Marshal(b, m, deterministic)
}
func (m *ReqProductDisplay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProductDisplay.Merge(m, src)
}
func (m *ReqProductDisplay) XXX_Size() int {
	return xxx_messageInfo_ReqProductDisplay.Size(m)
}
func (m *ReqProductDisplay) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProductDisplay.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProductDisplay proto.InternalMessageInfo

func (m *ReqProductDisplay) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqProductDisplay) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *ReqProductDisplay) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *ReqProductDisplay) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyProductInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *ProductInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyProductInfo) Reset()         { *m = ReplyProductInfo{} }
func (m *ReplyProductInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyProductInfo) ProtoMessage()    {}
func (*ReplyProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{6}
}

func (m *ReplyProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyProductInfo.Unmarshal(m, b)
}
func (m *ReplyProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyProductInfo.Marshal(b, m, deterministic)
}
func (m *ReplyProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyProductInfo.Merge(m, src)
}
func (m *ReplyProductInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyProductInfo.Size(m)
}
func (m *ReplyProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyProductInfo proto.InternalMessageInfo

func (m *ReplyProductInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyProductInfo) GetInfo() *ProductInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyProductList struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32         `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32         `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32         `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*ProductInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyProductList) Reset()         { *m = ReplyProductList{} }
func (m *ReplyProductList) String() string { return proto.CompactTextString(m) }
func (*ReplyProductList) ProtoMessage()    {}
func (*ReplyProductList) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{7}
}

func (m *ReplyProductList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyProductList.Unmarshal(m, b)
}
func (m *ReplyProductList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyProductList.Marshal(b, m, deterministic)
}
func (m *ReplyProductList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyProductList.Merge(m, src)
}
func (m *ReplyProductList) XXX_Size() int {
	return xxx_messageInfo_ReplyProductList.Size(m)
}
func (m *ReplyProductList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyProductList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyProductList proto.InternalMessageInfo

func (m *ReplyProductList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyProductList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyProductList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyProductList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyProductList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyProductList) GetList() []*ProductInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyProductDisplays struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*DisplayShow `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyProductDisplays) Reset()         { *m = ReplyProductDisplays{} }
func (m *ReplyProductDisplays) String() string { return proto.CompactTextString(m) }
func (*ReplyProductDisplays) ProtoMessage()    {}
func (*ReplyProductDisplays) Descriptor() ([]byte, []int) {
	return fileDescriptor_26f760d583f07007, []int{8}
}

func (m *ReplyProductDisplays) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyProductDisplays.Unmarshal(m, b)
}
func (m *ReplyProductDisplays) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyProductDisplays.Marshal(b, m, deterministic)
}
func (m *ReplyProductDisplays) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyProductDisplays.Merge(m, src)
}
func (m *ReplyProductDisplays) XXX_Size() int {
	return xxx_messageInfo_ReplyProductDisplays.Size(m)
}
func (m *ReplyProductDisplays) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyProductDisplays.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyProductDisplays proto.InternalMessageInfo

func (m *ReplyProductDisplays) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyProductDisplays) GetList() []*DisplayShow {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductInfo)(nil), "omo.msp.favorite.ProductInfo")
	proto.RegisterType((*ProductEffect)(nil), "omo.msp.favorite.ProductEffect")
	proto.RegisterType((*DisplayShow)(nil), "omo.msp.favorite.DisplayShow")
	proto.RegisterType((*ReqProductAdd)(nil), "omo.msp.favorite.ReqProductAdd")
	proto.RegisterType((*ReqProductUpdate)(nil), "omo.msp.favorite.ReqProductUpdate")
	proto.RegisterType((*ReqProductDisplay)(nil), "omo.msp.favorite.ReqProductDisplay")
	proto.RegisterType((*ReplyProductInfo)(nil), "omo.msp.favorite.ReplyProductInfo")
	proto.RegisterType((*ReplyProductList)(nil), "omo.msp.favorite.ReplyProductList")
	proto.RegisterType((*ReplyProductDisplays)(nil), "omo.msp.favorite.ReplyProductDisplays")
}

func init() {
	proto.RegisterFile("proto/favorite/product.proto", fileDescriptor_26f760d583f07007)
}

var fileDescriptor_26f760d583f07007 = []byte{
	// 874 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x5e, 0x27, 0x5e, 0x67, 0xf7, 0xa4, 0x4e, 0xd3, 0xd1, 0xaa, 0x1a, 0xa5, 0xc0, 0x5a, 0x46,
	0x42, 0x81, 0x8b, 0x54, 0x14, 0x21, 0xd4, 0xcb, 0xad, 0x80, 0x55, 0x25, 0x50, 0x2b, 0x07, 0xb8,
	0xe0, 0x02, 0xe1, 0xb5, 0x4f, 0xda, 0xd1, 0xda, 0x1e, 0xd7, 0x33, 0xde, 0x12, 0x09, 0x21, 0x9e,
	0x81, 0x77, 0xe0, 0x8d, 0x78, 0x0d, 0xde, 0x01, 0xcd, 0x8f, 0x13, 0x7b, 0x37, 0x7f, 0x50, 0xee,
	0xe6, 0x9b, 0x39, 0x73, 0xbe, 0xef, 0x9c, 0xf3, 0x79, 0x64, 0x78, 0xaf, 0xac, 0xb8, 0xe4, 0x8f,
	0x17, 0xf1, 0x0d, 0xaf, 0x98, 0xc4, 0xc7, 0x65, 0xc5, 0xd3, 0x3a, 0x91, 0x33, 0xbd, 0x4d, 0xc6,
	0x3c, 0xe7, 0xb3, 0x5c, 0x94, 0xb3, 0xe6, 0x7c, 0xf2, 0xe8, 0x56, 0x7c, 0xc2, 0xf3, 0x9c, 0x17,
	0x26, 0x3c, 0xfc, 0xd3, 0x85, 0xe1, 0x4b, 0x93, 0xe0, 0x79, 0xb1, 0xe0, 0x64, 0x0c, 0xfd, 0x9a,
	0xa5, 0xd4, 0x09, 0x9c, 0xe9, 0x69, 0xa4, 0x96, 0x64, 0x04, 0x3d, 0x96, 0xd2, 0x5e, 0xe0, 0x4c,
	0xdd, 0xa8, 0xc7, 0x52, 0x42, 0xc0, 0x95, 0xcb, 0x12, 0x69, 0x3f, 0x70, 0xa6, 0x7e, 0xa4, 0xd7,
	0x84, 0xc2, 0x20, 0xa9, 0x30, 0x96, 0x98, 0x52, 0x37, 0x70, 0xa6, 0xfd, 0xa8, 0x81, 0xea, 0xa4,
	0x2e, 0x53, 0x7d, 0x72, 0x6c, 0x4e, 0x2c, 0x5c, 0xdd, 0xe1, 0x15, 0xf5, 0x34, 0x5b, 0x03, 0xc9,
	0x04, 0x4e, 0x78, 0x89, 0x95, 0x3e, 0x1a, 0xe8, 0xa3, 0x15, 0x56, 0xec, 0x45, 0x9c, 0x23, 0x3d,
	0xd1, 0xfb, 0x7a, 0x4d, 0xce, 0xe0, 0x38, 0xc7, 0xa2, 0x16, 0xf4, 0x54, 0x6f, 0x1a, 0xa0, 0x2a,
	0xb9, 0xc6, 0x25, 0x1d, 0x9a, 0x4a, 0xae, 0x71, 0xa9, 0x18, 0x25, 0xe6, 0x65, 0x86, 0x92, 0xde,
	0x33, 0x8c, 0x16, 0x2a, 0xc6, 0x24, 0x96, 0x71, 0xc6, 0x5f, 0x09, 0xea, 0x1b, 0xc6, 0x06, 0x93,
	0x87, 0xe0, 0x09, 0x19, 0xcb, 0x5a, 0xd0, 0x91, 0xae, 0xd8, 0x22, 0xb5, 0x5f, 0x61, 0x1e, 0x57,
	0xd7, 0xf4, 0xbe, 0xbe, 0x61, 0x91, 0x52, 0x93, 0xb1, 0x9c, 0x49, 0x3a, 0xd6, 0xe1, 0x06, 0x28,
	0x6e, 0x2c, 0x64, 0xc5, 0x50, 0xd0, 0x0f, 0x82, 0xbe, 0xe2, 0xb6, 0x50, 0x9d, 0x54, 0x78, 0xc3,
	0x04, 0x0a, 0x7a, 0x6e, 0x4e, 0x2c, 0x54, 0x99, 0xc4, 0x6b, 0xfe, 0x56, 0xd0, 0x40, 0xef, 0x1b,
	0x40, 0x9e, 0xc2, 0x00, 0x17, 0x0b, 0x4c, 0xa4, 0xa0, 0x1f, 0x07, 0xfd, 0xe9, 0xf0, 0xc9, 0xf9,
	0xec, 0xf6, 0xc8, 0x67, 0x76, 0xa2, 0x5f, 0xe9, 0xb8, 0xa8, 0x89, 0x27, 0x4f, 0xe1, 0x24, 0x65,
	0xa2, 0xcc, 0xe2, 0xa5, 0xa0, 0x9f, 0xe8, 0xbb, 0xef, 0xdf, 0xbd, 0xfb, 0xa5, 0x89, 0x98, 0xbf,
	0xe6, 0x6f, 0xa3, 0x55, 0x78, 0x88, 0xe0, 0x77, 0x92, 0x2a, 0xd9, 0x65, 0x2c, 0x25, 0x56, 0x85,
	0x35, 0x4b, 0x03, 0x55, 0xe3, 0x73, 0x56, 0x68, 0xc7, 0xf8, 0x91, 0x5a, 0xea, 0x9d, 0xf8, 0x17,
	0xeb, 0x18, 0xb5, 0x54, 0xcd, 0x8b, 0x93, 0x04, 0x85, 0xd0, 0x7e, 0xf1, 0x23, 0x8b, 0xc2, 0x2f,
	0x60, 0xd8, 0xe2, 0xdf, 0xe0, 0xc6, 0x87, 0xe0, 0x99, 0x6a, 0x74, 0xfe, 0xd3, 0xc8, 0xa2, 0xf0,
	0xef, 0x1e, 0xf8, 0x11, 0xbe, 0xb1, 0x1a, 0x2f, 0xd2, 0x74, 0xe5, 0x14, 0xa7, 0xe5, 0x14, 0xeb,
	0x89, 0xde, 0xda, 0x13, 0x2b, 0xef, 0xb8, 0x6d, 0xef, 0xb4, 0x1d, 0x78, 0x7c, 0xd7, 0x81, 0xda,
	0xff, 0x5e, 0xd7, 0xff, 0x8d, 0xb3, 0x06, 0x5d, 0x67, 0xad, 0x5d, 0x72, 0xd2, 0x71, 0x49, 0xcb,
	0x0f, 0xe3, 0xad, 0x7e, 0x78, 0xb0, 0xc5, 0x0f, 0x64, 0x8b, 0x1f, 0xce, 0xdf, 0xc1, 0x0f, 0xc1,
	0xbf, 0xf3, 0xc3, 0x6f, 0x30, 0x5e, 0xb7, 0xfb, 0x7b, 0xfd, 0x49, 0x6f, 0x98, 0xd6, 0xdd, 0x7e,
	0x37, 0x53, 0xe9, 0xb7, 0xa6, 0xb2, 0xee, 0x91, 0xdb, 0xe9, 0xd1, 0x8e, 0x29, 0x84, 0x02, 0x1e,
	0xac, 0xf9, 0xad, 0xc4, 0x0d, 0x02, 0x28, 0x0c, 0xac, 0x64, 0x2b, 0xa2, 0x81, 0x2d, 0x23, 0xf5,
	0xdb, 0x46, 0xea, 0x90, 0xba, 0xb7, 0x48, 0x7f, 0x55, 0x45, 0x97, 0xd9, 0xb2, 0xfd, 0x60, 0x7e,
	0xbe, 0x7a, 0x1e, 0x14, 0xed, 0xc6, 0x0e, 0xea, 0x3b, 0x73, 0x1d, 0xb4, 0x7a, 0x3d, 0x3e, 0x05,
	0x97, 0x15, 0x0b, 0xae, 0x55, 0x6d, 0xbc, 0xd4, 0xe2, 0x88, 0x74, 0x68, 0xf8, 0x97, 0xd3, 0xa5,
	0xff, 0x86, 0x09, 0xf9, 0x5f, 0xe9, 0xcf, 0xe0, 0x58, 0x72, 0x19, 0x67, 0xf6, 0x2b, 0x35, 0x40,
	0xed, 0x96, 0xf1, 0x2b, 0x14, 0xf6, 0x4b, 0x35, 0x40, 0x8d, 0x4c, 0x2d, 0xec, 0x97, 0xaa, 0xd7,
	0xaa, 0x7b, 0x45, 0x9d, 0x5f, 0xa1, 0x19, 0x8c, 0x1f, 0x59, 0xa4, 0xca, 0xca, 0x98, 0x90, 0xda,
	0xd3, 0xfb, 0xcb, 0x52, 0xa1, 0xe1, 0xef, 0x0e, 0x9c, 0xb5, 0xcb, 0xb2, 0xc3, 0x14, 0xef, 0xd0,
	0xd9, 0xdd, 0x12, 0xda, 0x86, 0xd6, 0xa1, 0x4f, 0xfe, 0xf0, 0x60, 0x64, 0xd9, 0xe7, 0x58, 0xdd,
	0xb0, 0x04, 0xc9, 0x0b, 0xf0, 0x2e, 0xd2, 0xf4, 0x45, 0x81, 0xe4, 0x7c, 0x13, 0x6d, 0xeb, 0xa1,
	0x99, 0x84, 0x5b, 0x74, 0xb5, 0x4a, 0x0d, 0x8f, 0xc8, 0xb7, 0xe0, 0x5d, 0xa2, 0x54, 0x09, 0x37,
	0xd6, 0xf1, 0xa6, 0x46, 0xa1, 0x43, 0x0f, 0x4c, 0xf7, 0x1d, 0x0c, 0x2f, 0x51, 0x3e, 0x5b, 0x7e,
	0xcd, 0x32, 0x89, 0xd5, 0x16, 0x91, 0x2a, 0xa7, 0x09, 0xd8, 0x97, 0x55, 0x79, 0x29, 0x3c, 0x22,
	0x73, 0xb8, 0x77, 0x89, 0x52, 0x35, 0x94, 0x09, 0xc9, 0x92, 0xfd, 0x69, 0x83, 0x1d, 0x33, 0xd1,
	0x29, 0xc2, 0x23, 0xf2, 0x12, 0x46, 0xe6, 0x81, 0x38, 0x40, 0xad, 0x09, 0x9c, 0x3c, 0xda, 0x92,
	0xd6, 0x16, 0xff, 0x03, 0x80, 0xcd, 0x18, 0x0b, 0x24, 0xe1, 0xae, 0x01, 0xd9, 0x84, 0x87, 0x35,
	0xf5, 0x39, 0x9c, 0x46, 0x98, 0xf3, 0x1b, 0x3c, 0x60, 0x4c, 0x7b, 0x24, 0xfe, 0x04, 0xfe, 0x45,
	0x59, 0x62, 0x91, 0x36, 0x6f, 0xd3, 0x87, 0xbb, 0x54, 0xda, 0xa0, 0xc9, 0x47, 0xbb, 0x65, 0x36,
	0x9f, 0x46, 0x78, 0x44, 0x7e, 0x86, 0xfb, 0xf3, 0xfa, 0x4a, 0x56, 0xf1, 0xfa, 0xf5, 0xfb, 0x7f,
	0x19, 0x9e, 0x8d, 0x7f, 0x1c, 0x75, 0x7f, 0x1c, 0xaf, 0x3c, 0x8d, 0x3f, 0xfb, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x05, 0x2c, 0x5a, 0x7f, 0x81, 0x0a, 0x00, 0x00,
}
