// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/favorite/sheet.proto

package favorite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SheetInfo struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64            `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64            `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Name                 string           `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string           `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Remark               string           `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Creator              string           `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string           `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	Quote                string           `protobuf:"bytes,10,opt,name=quote,proto3" json:"quote,omitempty"`
	Status               uint32           `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Type                 uint32           `protobuf:"varint,12,opt,name=type,proto3" json:"type,omitempty"`
	Contents             []*ContentWeight `protobuf:"bytes,21,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SheetInfo) Reset()         { *m = SheetInfo{} }
func (m *SheetInfo) String() string { return proto.CompactTextString(m) }
func (*SheetInfo) ProtoMessage()    {}
func (*SheetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{0}
}

func (m *SheetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SheetInfo.Unmarshal(m, b)
}
func (m *SheetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SheetInfo.Marshal(b, m, deterministic)
}
func (m *SheetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SheetInfo.Merge(m, src)
}
func (m *SheetInfo) XXX_Size() int {
	return xxx_messageInfo_SheetInfo.Size(m)
}
func (m *SheetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SheetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SheetInfo proto.InternalMessageInfo

func (m *SheetInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SheetInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SheetInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SheetInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *SheetInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SheetInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SheetInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *SheetInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *SheetInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *SheetInfo) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *SheetInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SheetInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *SheetInfo) GetContents() []*ContentWeight {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ContentWeight struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Weight               uint32   `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentWeight) Reset()         { *m = ContentWeight{} }
func (m *ContentWeight) String() string { return proto.CompactTextString(m) }
func (*ContentWeight) ProtoMessage()    {}
func (*ContentWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{1}
}

func (m *ContentWeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentWeight.Unmarshal(m, b)
}
func (m *ContentWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentWeight.Marshal(b, m, deterministic)
}
func (m *ContentWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentWeight.Merge(m, src)
}
func (m *ContentWeight) XXX_Size() int {
	return xxx_messageInfo_ContentWeight.Size(m)
}
func (m *ContentWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentWeight.DiscardUnknown(m)
}

var xxx_messageInfo_ContentWeight proto.InternalMessageInfo

func (m *ContentWeight) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ContentWeight) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ReqSheetAdd struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string           `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Remark               string           `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string           `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Quote                string           `protobuf:"bytes,5,opt,name=quote,proto3" json:"quote,omitempty"`
	Status               uint32           `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Type                 uint32           `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	Keys                 []*ContentWeight `protobuf:"bytes,18,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqSheetAdd) Reset()         { *m = ReqSheetAdd{} }
func (m *ReqSheetAdd) String() string { return proto.CompactTextString(m) }
func (*ReqSheetAdd) ProtoMessage()    {}
func (*ReqSheetAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{2}
}

func (m *ReqSheetAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSheetAdd.Unmarshal(m, b)
}
func (m *ReqSheetAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSheetAdd.Marshal(b, m, deterministic)
}
func (m *ReqSheetAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSheetAdd.Merge(m, src)
}
func (m *ReqSheetAdd) XXX_Size() int {
	return xxx_messageInfo_ReqSheetAdd.Size(m)
}
func (m *ReqSheetAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSheetAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSheetAdd proto.InternalMessageInfo

func (m *ReqSheetAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqSheetAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqSheetAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqSheetAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqSheetAdd) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *ReqSheetAdd) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqSheetAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqSheetAdd) GetKeys() []*ContentWeight {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ReqSheetUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSheetUpdate) Reset()         { *m = ReqSheetUpdate{} }
func (m *ReqSheetUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqSheetUpdate) ProtoMessage()    {}
func (*ReqSheetUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{3}
}

func (m *ReqSheetUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSheetUpdate.Unmarshal(m, b)
}
func (m *ReqSheetUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSheetUpdate.Marshal(b, m, deterministic)
}
func (m *ReqSheetUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSheetUpdate.Merge(m, src)
}
func (m *ReqSheetUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqSheetUpdate.Size(m)
}
func (m *ReqSheetUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSheetUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSheetUpdate proto.InternalMessageInfo

func (m *ReqSheetUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSheetUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqSheetUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqSheetUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqSheetContent struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Weight               uint32   `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSheetContent) Reset()         { *m = ReqSheetContent{} }
func (m *ReqSheetContent) String() string { return proto.CompactTextString(m) }
func (*ReqSheetContent) ProtoMessage()    {}
func (*ReqSheetContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{4}
}

func (m *ReqSheetContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSheetContent.Unmarshal(m, b)
}
func (m *ReqSheetContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSheetContent.Marshal(b, m, deterministic)
}
func (m *ReqSheetContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSheetContent.Merge(m, src)
}
func (m *ReqSheetContent) XXX_Size() int {
	return xxx_messageInfo_ReqSheetContent.Size(m)
}
func (m *ReqSheetContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSheetContent.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSheetContent proto.InternalMessageInfo

func (m *ReqSheetContent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSheetContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReqSheetContent) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ReqSheetContent) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplySheetInfo struct {
	Info                 *SheetInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplySheetInfo) Reset()         { *m = ReplySheetInfo{} }
func (m *ReplySheetInfo) String() string { return proto.CompactTextString(m) }
func (*ReplySheetInfo) ProtoMessage()    {}
func (*ReplySheetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{5}
}

func (m *ReplySheetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplySheetInfo.Unmarshal(m, b)
}
func (m *ReplySheetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplySheetInfo.Marshal(b, m, deterministic)
}
func (m *ReplySheetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplySheetInfo.Merge(m, src)
}
func (m *ReplySheetInfo) XXX_Size() int {
	return xxx_messageInfo_ReplySheetInfo.Size(m)
}
func (m *ReplySheetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplySheetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplySheetInfo proto.InternalMessageInfo

func (m *ReplySheetInfo) GetInfo() *SheetInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplySheetInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplySheetList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32       `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32       `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32       `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*SheetInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplySheetList) Reset()         { *m = ReplySheetList{} }
func (m *ReplySheetList) String() string { return proto.CompactTextString(m) }
func (*ReplySheetList) ProtoMessage()    {}
func (*ReplySheetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{6}
}

func (m *ReplySheetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplySheetList.Unmarshal(m, b)
}
func (m *ReplySheetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplySheetList.Marshal(b, m, deterministic)
}
func (m *ReplySheetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplySheetList.Merge(m, src)
}
func (m *ReplySheetList) XXX_Size() int {
	return xxx_messageInfo_ReplySheetList.Size(m)
}
func (m *ReplySheetList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplySheetList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplySheetList proto.InternalMessageInfo

func (m *ReplySheetList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplySheetList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplySheetList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplySheetList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplySheetList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplySheetList) GetList() []*SheetInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqSheetKeys struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string           `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Keys                 []*ContentWeight `protobuf:"bytes,14,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqSheetKeys) Reset()         { *m = ReqSheetKeys{} }
func (m *ReqSheetKeys) String() string { return proto.CompactTextString(m) }
func (*ReqSheetKeys) ProtoMessage()    {}
func (*ReqSheetKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{7}
}

func (m *ReqSheetKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSheetKeys.Unmarshal(m, b)
}
func (m *ReqSheetKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSheetKeys.Marshal(b, m, deterministic)
}
func (m *ReqSheetKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSheetKeys.Merge(m, src)
}
func (m *ReqSheetKeys) XXX_Size() int {
	return xxx_messageInfo_ReqSheetKeys.Size(m)
}
func (m *ReqSheetKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSheetKeys.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSheetKeys proto.InternalMessageInfo

func (m *ReqSheetKeys) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSheetKeys) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqSheetKeys) GetKeys() []*ContentWeight {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ReplySheetKeys struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Keys                 []*ContentWeight `protobuf:"bytes,12,rep,name=keys,proto3" json:"keys,omitempty"`
	Status               *ReplyStatus     `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReplySheetKeys) Reset()         { *m = ReplySheetKeys{} }
func (m *ReplySheetKeys) String() string { return proto.CompactTextString(m) }
func (*ReplySheetKeys) ProtoMessage()    {}
func (*ReplySheetKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b069a08912f5ab7, []int{8}
}

func (m *ReplySheetKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplySheetKeys.Unmarshal(m, b)
}
func (m *ReplySheetKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplySheetKeys.Marshal(b, m, deterministic)
}
func (m *ReplySheetKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplySheetKeys.Merge(m, src)
}
func (m *ReplySheetKeys) XXX_Size() int {
	return xxx_messageInfo_ReplySheetKeys.Size(m)
}
func (m *ReplySheetKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplySheetKeys.DiscardUnknown(m)
}

var xxx_messageInfo_ReplySheetKeys proto.InternalMessageInfo

func (m *ReplySheetKeys) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplySheetKeys) GetKeys() []*ContentWeight {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *ReplySheetKeys) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*SheetInfo)(nil), "omo.msp.favorite.SheetInfo")
	proto.RegisterType((*ContentWeight)(nil), "omo.msp.favorite.ContentWeight")
	proto.RegisterType((*ReqSheetAdd)(nil), "omo.msp.favorite.ReqSheetAdd")
	proto.RegisterType((*ReqSheetUpdate)(nil), "omo.msp.favorite.ReqSheetUpdate")
	proto.RegisterType((*ReqSheetContent)(nil), "omo.msp.favorite.ReqSheetContent")
	proto.RegisterType((*ReplySheetInfo)(nil), "omo.msp.favorite.ReplySheetInfo")
	proto.RegisterType((*ReplySheetList)(nil), "omo.msp.favorite.ReplySheetList")
	proto.RegisterType((*ReqSheetKeys)(nil), "omo.msp.favorite.ReqSheetKeys")
	proto.RegisterType((*ReplySheetKeys)(nil), "omo.msp.favorite.ReplySheetKeys")
}

func init() {
	proto.RegisterFile("proto/favorite/sheet.proto", fileDescriptor_2b069a08912f5ab7)
}

var fileDescriptor_2b069a08912f5ab7 = []byte{
	// 747 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4d, 0x4f, 0xdb, 0x4c,
	0x10, 0xc6, 0xce, 0x17, 0x99, 0x7c, 0xbc, 0xd1, 0xea, 0x7d, 0x91, 0x15, 0xf4, 0x42, 0xea, 0x53,
	0x4e, 0x41, 0x02, 0xf5, 0x50, 0xf5, 0x04, 0x95, 0x8a, 0x10, 0xad, 0x8a, 0x1c, 0x55, 0x95, 0x7a,
	0x33, 0xf1, 0x00, 0x2e, 0xb1, 0xd7, 0xb1, 0x37, 0xd0, 0xfc, 0x84, 0x5e, 0xfa, 0xdb, 0x7a, 0xec,
	0xb9, 0xbf, 0xa4, 0xda, 0x59, 0x6f, 0x70, 0xc0, 0x0e, 0x8e, 0xb8, 0xed, 0xec, 0x3c, 0xfb, 0xcc,
	0xcc, 0xf3, 0x8c, 0xa3, 0x40, 0x3f, 0x8a, 0xb9, 0xe0, 0x07, 0x57, 0xee, 0x1d, 0x8f, 0x7d, 0x81,
	0x07, 0xc9, 0x0d, 0xa2, 0x18, 0xd1, 0x25, 0xeb, 0xf1, 0x80, 0x8f, 0x82, 0x24, 0x1a, 0xe9, 0x6c,
	0x7f, 0xf7, 0x11, 0x7a, 0xc2, 0x83, 0x80, 0x87, 0x0a, 0x6e, 0xff, 0x36, 0xa1, 0x39, 0x96, 0xcf,
	0xcf, 0xc2, 0x2b, 0xce, 0x7a, 0x50, 0x99, 0xfb, 0x9e, 0x65, 0x0c, 0x8c, 0x61, 0xd3, 0x91, 0x47,
	0xd6, 0x05, 0xd3, 0xf7, 0x2c, 0x73, 0x60, 0x0c, 0xab, 0x8e, 0xe9, 0x7b, 0xcc, 0x82, 0xc6, 0x24,
	0x46, 0x57, 0xa0, 0x67, 0x55, 0x06, 0xc6, 0xb0, 0xe2, 0xe8, 0x50, 0x66, 0xe6, 0x91, 0x47, 0x99,
	0xaa, 0xca, 0xa4, 0x21, 0x63, 0x50, 0x0d, 0xdd, 0x00, 0xad, 0x1a, 0xd1, 0xd2, 0x99, 0xfd, 0x0b,
	0x35, 0x7e, 0x1f, 0x62, 0x6c, 0xd5, 0xe9, 0x52, 0x05, 0x6c, 0x07, 0xea, 0x31, 0x06, 0x6e, 0x7c,
	0x6b, 0x35, 0xe8, 0x3a, 0x8d, 0x96, 0x55, 0x79, 0x6c, 0x6d, 0x53, 0x42, 0x87, 0xac, 0x0f, 0xdb,
	0x3c, 0xc2, 0x98, 0x52, 0x4d, 0x4a, 0x2d, 0x63, 0x59, 0x63, 0x36, 0xe7, 0x02, 0x2d, 0x50, 0x35,
	0x28, 0x90, 0x35, 0x12, 0xe1, 0x8a, 0x79, 0x62, 0xb5, 0x06, 0xc6, 0xb0, 0xe3, 0xa4, 0x91, 0xec,
	0x52, 0x2c, 0x22, 0xb4, 0xda, 0x74, 0x4b, 0x67, 0xf6, 0x16, 0xb6, 0x27, 0x3c, 0x14, 0x18, 0x8a,
	0xc4, 0xfa, 0x6f, 0x50, 0x19, 0xb6, 0x0e, 0xf7, 0x47, 0x8f, 0xf5, 0x1d, 0xbd, 0x53, 0x88, 0x2f,
	0xe8, 0x5f, 0xdf, 0x08, 0x67, 0xf9, 0xc0, 0x7e, 0x03, 0x9d, 0x95, 0x54, 0x8e, 0xba, 0x3b, 0x50,
	0xbf, 0xa7, 0x1c, 0x29, 0xdc, 0x71, 0xd2, 0xc8, 0xfe, 0x63, 0x40, 0xcb, 0xc1, 0x19, 0x19, 0x73,
	0xec, 0x3d, 0x28, 0x68, 0xe4, 0x29, 0x68, 0xe6, 0x2b, 0x58, 0x59, 0x51, 0x30, 0xab, 0x53, 0xb5,
	0x48, 0xa7, 0x5a, 0xbe, 0x4e, 0xf5, 0x5c, 0x9d, 0x1a, 0x19, 0x9d, 0x8e, 0xa0, 0x7a, 0x8b, 0x8b,
	0xc4, 0x62, 0xe5, 0x34, 0x22, 0xb0, 0xfd, 0x0d, 0xba, 0x7a, 0xc6, 0xcf, 0xb4, 0x29, 0x39, 0x02,
	0xe9, 0xc1, 0xcd, 0xcc, 0xe0, 0x65, 0x46, 0xac, 0xad, 0x8e, 0x68, 0xcf, 0xe0, 0x1f, 0x5d, 0x2b,
	0x6d, 0x25, 0xa7, 0x98, 0xdc, 0x32, 0x95, 0x4c, 0xeb, 0xe9, 0x30, 0xe3, 0x53, 0x25, 0xeb, 0xd3,
	0x3a, 0x55, 0xed, 0xef, 0x72, 0xbc, 0x68, 0xba, 0x78, 0xf8, 0xba, 0x0e, 0xa0, 0xea, 0x87, 0x57,
	0x9c, 0x4a, 0xb6, 0x0e, 0x77, 0x9f, 0xaa, 0xb4, 0x84, 0x3a, 0x04, 0x64, 0xaf, 0x97, 0x16, 0x98,
	0xf4, 0xe4, 0xff, 0xa7, 0x4f, 0x54, 0x09, 0x02, 0x69, 0x87, 0xec, 0x5f, 0x46, 0xb6, 0xf4, 0x07,
	0x3f, 0x11, 0x19, 0x26, 0x63, 0x03, 0x26, 0xb9, 0x19, 0x82, 0x0b, 0x77, 0x9a, 0xae, 0xa7, 0x0a,
	0xe4, 0x6d, 0xe4, 0x5e, 0x63, 0x92, 0x8a, 0xa1, 0x02, 0x69, 0x95, 0x3c, 0x90, 0x0e, 0x1d, 0x87,
	0xce, 0x52, 0xb7, 0x70, 0x1e, 0x5c, 0xa2, 0x32, 0xa4, 0xe3, 0xa4, 0x91, 0x54, 0x62, 0xea, 0x27,
	0xc2, 0xea, 0xd1, 0xbe, 0xac, 0x57, 0x42, 0x02, 0xed, 0x19, 0xb4, 0xb5, 0x7f, 0xe7, 0xb8, 0x48,
	0x72, 0xcc, 0xcb, 0x5a, 0x61, 0x3e, 0x5a, 0x70, 0xbd, 0x9e, 0xdd, 0x4d, 0xd6, 0xf3, 0xe7, 0x8a,
	0x8a, 0x05, 0x55, 0x35, 0x73, 0x7b, 0x03, 0xe6, 0x8c, 0x19, 0x95, 0x0d, 0xcc, 0x38, 0xfc, 0xd1,
	0x80, 0x36, 0xf5, 0x32, 0xc6, 0xf8, 0xce, 0x9f, 0x20, 0x3b, 0x87, 0xfa, 0xb1, 0xe7, 0x7d, 0x0a,
	0x91, 0xe5, 0x32, 0x2c, 0x7f, 0x3e, 0xfa, 0x83, 0xa2, 0x02, 0x5a, 0x65, 0x7b, 0x4b, 0x92, 0x9d,
	0xa2, 0x28, 0x26, 0x9b, 0x63, 0x42, 0xd0, 0x52, 0x64, 0x0e, 0xb4, 0x4e, 0x51, 0x9c, 0x2c, 0xde,
	0xfb, 0x53, 0x81, 0x31, 0xdb, 0x2f, 0x64, 0x54, 0x80, 0xf5, 0x9c, 0x72, 0x81, 0xed, 0x2d, 0x36,
	0x86, 0xf6, 0x29, 0x0a, 0xa9, 0x89, 0x9f, 0x08, 0x7f, 0xf2, 0x02, 0x52, 0x4d, 0x61, 0x6f, 0xb1,
	0x0b, 0xe8, 0xaa, 0xdf, 0x9e, 0x12, 0xbd, 0x2a, 0x60, 0x7f, 0xb7, 0x80, 0x76, 0x39, 0x3a, 0xa4,
	0x8c, 0x6e, 0x82, 0x6c, 0x50, 0x6c, 0x4c, 0x4a, 0x57, 0x46, 0xce, 0x8f, 0xd0, 0x56, 0x68, 0xb5,
	0x11, 0x6c, 0xaf, 0xb0, 0x47, 0x09, 0x78, 0xb6, 0xc5, 0x33, 0x68, 0x3a, 0x18, 0xf0, 0x3b, 0x2c,
	0xe1, 0xf6, 0x33, 0x54, 0x17, 0x7a, 0x5a, 0xfa, 0x3e, 0xf6, 0x8a, 0xa7, 0x95, 0xf9, 0xf5, 0xb3,
	0x4a, 0x04, 0xe9, 0xd7, 0x3c, 0x8e, 0x22, 0x0c, 0xbd, 0x73, 0x5c, 0xb0, 0x57, 0xc5, 0x84, 0xe9,
	0x87, 0x55, 0x8a, 0xf3, 0x02, 0x5a, 0xe3, 0xf9, 0xa5, 0x88, 0xdd, 0x89, 0xbc, 0x79, 0xd1, 0x82,
	0x2b, 0xc6, 0x93, 0xde, 0xd7, 0xee, 0xea, 0xbf, 0xaa, 0xcb, 0x3a, 0xc5, 0x47, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x0d, 0x14, 0x6f, 0xf7, 0x9c, 0x09, 0x00, 0x00,
}
