// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/favorite/template.proto

package favorite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductTemplateInfo struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64            `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64            `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string           `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string           `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string           `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Keywords             string           `protobuf:"bytes,8,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Status               uint32           `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Remark               string           `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	Frame                string           `protobuf:"bytes,12,opt,name=frame,proto3" json:"frame,omitempty"`
	Asset                string           `protobuf:"bytes,13,opt,name=asset,proto3" json:"asset,omitempty"`
	Env                  string           `protobuf:"bytes,14,opt,name=env,proto3" json:"env,omitempty"`
	Graph                *ProductGraph    `protobuf:"bytes,19,opt,name=graph,proto3" json:"graph,omitempty"`
	Depends              []*ReferenceInfo `protobuf:"bytes,20,rep,name=depends,proto3" json:"depends,omitempty"`
	Bootloader           []*ReferenceInfo `protobuf:"bytes,21,rep,name=bootloader,proto3" json:"bootloader,omitempty"`
	Modules              []*PairInfo      `protobuf:"bytes,31,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProductTemplateInfo) Reset()         { *m = ProductTemplateInfo{} }
func (m *ProductTemplateInfo) String() string { return proto.CompactTextString(m) }
func (*ProductTemplateInfo) ProtoMessage()    {}
func (*ProductTemplateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{0}
}

func (m *ProductTemplateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductTemplateInfo.Unmarshal(m, b)
}
func (m *ProductTemplateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductTemplateInfo.Marshal(b, m, deterministic)
}
func (m *ProductTemplateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductTemplateInfo.Merge(m, src)
}
func (m *ProductTemplateInfo) XXX_Size() int {
	return xxx_messageInfo_ProductTemplateInfo.Size(m)
}
func (m *ProductTemplateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductTemplateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProductTemplateInfo proto.InternalMessageInfo

func (m *ProductTemplateInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ProductTemplateInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductTemplateInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ProductTemplateInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ProductTemplateInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ProductTemplateInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ProductTemplateInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductTemplateInfo) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *ProductTemplateInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ProductTemplateInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ProductTemplateInfo) GetFrame() string {
	if m != nil {
		return m.Frame
	}
	return ""
}

func (m *ProductTemplateInfo) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *ProductTemplateInfo) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *ProductTemplateInfo) GetGraph() *ProductGraph {
	if m != nil {
		return m.Graph
	}
	return nil
}

func (m *ProductTemplateInfo) GetDepends() []*ReferenceInfo {
	if m != nil {
		return m.Depends
	}
	return nil
}

func (m *ProductTemplateInfo) GetBootloader() []*ReferenceInfo {
	if m != nil {
		return m.Bootloader
	}
	return nil
}

func (m *ProductTemplateInfo) GetModules() []*PairInfo {
	if m != nil {
		return m.Modules
	}
	return nil
}

type ProductTemplateResult struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64         `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64         `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string        `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string        `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string        `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Keywords             string        `protobuf:"bytes,8,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Status               uint32        `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Remark               string        `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	UpdateCfg            string        `protobuf:"bytes,21,opt,name=updateCfg,proto3" json:"updateCfg,omitempty"`
	BootloaderCfg        string        `protobuf:"bytes,22,opt,name=bootloaderCfg,proto3" json:"bootloaderCfg,omitempty"`
	DependsCfg           string        `protobuf:"bytes,23,opt,name=dependsCfg,proto3" json:"dependsCfg,omitempty"`
	Graph                *ProductGraph `protobuf:"bytes,30,opt,name=graph,proto3" json:"graph,omitempty"`
	Modules              []*PairInfo   `protobuf:"bytes,31,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProductTemplateResult) Reset()         { *m = ProductTemplateResult{} }
func (m *ProductTemplateResult) String() string { return proto.CompactTextString(m) }
func (*ProductTemplateResult) ProtoMessage()    {}
func (*ProductTemplateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{1}
}

func (m *ProductTemplateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductTemplateResult.Unmarshal(m, b)
}
func (m *ProductTemplateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductTemplateResult.Marshal(b, m, deterministic)
}
func (m *ProductTemplateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductTemplateResult.Merge(m, src)
}
func (m *ProductTemplateResult) XXX_Size() int {
	return xxx_messageInfo_ProductTemplateResult.Size(m)
}
func (m *ProductTemplateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductTemplateResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProductTemplateResult proto.InternalMessageInfo

func (m *ProductTemplateResult) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ProductTemplateResult) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductTemplateResult) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ProductTemplateResult) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ProductTemplateResult) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ProductTemplateResult) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ProductTemplateResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductTemplateResult) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *ProductTemplateResult) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ProductTemplateResult) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ProductTemplateResult) GetUpdateCfg() string {
	if m != nil {
		return m.UpdateCfg
	}
	return ""
}

func (m *ProductTemplateResult) GetBootloaderCfg() string {
	if m != nil {
		return m.BootloaderCfg
	}
	return ""
}

func (m *ProductTemplateResult) GetDependsCfg() string {
	if m != nil {
		return m.DependsCfg
	}
	return ""
}

func (m *ProductTemplateResult) GetGraph() *ProductGraph {
	if m != nil {
		return m.Graph
	}
	return nil
}

func (m *ProductTemplateResult) GetModules() []*PairInfo {
	if m != nil {
		return m.Modules
	}
	return nil
}

type ReferenceInfo struct {
	Kind                 uint32   `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Org                  string   `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Weight               string   `protobuf:"bytes,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReferenceInfo) Reset()         { *m = ReferenceInfo{} }
func (m *ReferenceInfo) String() string { return proto.CompactTextString(m) }
func (*ReferenceInfo) ProtoMessage()    {}
func (*ReferenceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{2}
}

func (m *ReferenceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceInfo.Unmarshal(m, b)
}
func (m *ReferenceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceInfo.Marshal(b, m, deterministic)
}
func (m *ReferenceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceInfo.Merge(m, src)
}
func (m *ReferenceInfo) XXX_Size() int {
	return xxx_messageInfo_ReferenceInfo.Size(m)
}
func (m *ReferenceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceInfo proto.InternalMessageInfo

func (m *ReferenceInfo) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *ReferenceInfo) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *ReferenceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReferenceInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ReferenceInfo) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

type ProductGraph struct {
	Quality              uint32   `protobuf:"varint,1,opt,name=quality,proto3" json:"quality,omitempty"`
	Fps                  uint32   `protobuf:"varint,2,opt,name=fps,proto3" json:"fps,omitempty"`
	RunWidth             uint32   `protobuf:"varint,3,opt,name=runWidth,proto3" json:"runWidth,omitempty"`
	RunHeight            uint32   `protobuf:"varint,4,opt,name=runHeight,proto3" json:"runHeight,omitempty"`
	DesignWidth          uint32   `protobuf:"varint,5,opt,name=designWidth,proto3" json:"designWidth,omitempty"`
	DesignHeight         uint32   `protobuf:"varint,6,opt,name=designHeight,proto3" json:"designHeight,omitempty"`
	Weight               uint32   `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductGraph) Reset()         { *m = ProductGraph{} }
func (m *ProductGraph) String() string { return proto.CompactTextString(m) }
func (*ProductGraph) ProtoMessage()    {}
func (*ProductGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{3}
}

func (m *ProductGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductGraph.Unmarshal(m, b)
}
func (m *ProductGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductGraph.Marshal(b, m, deterministic)
}
func (m *ProductGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductGraph.Merge(m, src)
}
func (m *ProductGraph) XXX_Size() int {
	return xxx_messageInfo_ProductGraph.Size(m)
}
func (m *ProductGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductGraph.DiscardUnknown(m)
}

var xxx_messageInfo_ProductGraph proto.InternalMessageInfo

func (m *ProductGraph) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *ProductGraph) GetFps() uint32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *ProductGraph) GetRunWidth() uint32 {
	if m != nil {
		return m.RunWidth
	}
	return 0
}

func (m *ProductGraph) GetRunHeight() uint32 {
	if m != nil {
		return m.RunHeight
	}
	return 0
}

func (m *ProductGraph) GetDesignWidth() uint32 {
	if m != nil {
		return m.DesignWidth
	}
	return 0
}

func (m *ProductGraph) GetDesignHeight() uint32 {
	if m != nil {
		return m.DesignHeight
	}
	return 0
}

func (m *ProductGraph) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ReqProductTemplateAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Env                  string   `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	Frame                string   `protobuf:"bytes,7,opt,name=frame,proto3" json:"frame,omitempty"`
	Asset                string   `protobuf:"bytes,8,opt,name=asset,proto3" json:"asset,omitempty"`
	Fps                  uint32   `protobuf:"varint,10,opt,name=fps,proto3" json:"fps,omitempty"`
	Quality              uint32   `protobuf:"varint,11,opt,name=quality,proto3" json:"quality,omitempty"`
	RunWidth             uint32   `protobuf:"varint,12,opt,name=runWidth,proto3" json:"runWidth,omitempty"`
	RunHeight            uint32   `protobuf:"varint,13,opt,name=runHeight,proto3" json:"runHeight,omitempty"`
	DesignWidth          uint32   `protobuf:"varint,14,opt,name=designWidth,proto3" json:"designWidth,omitempty"`
	DesignHeight         uint32   `protobuf:"varint,15,opt,name=designHeight,proto3" json:"designHeight,omitempty"`
	Weight               uint32   `protobuf:"varint,16,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqProductTemplateAdd) Reset()         { *m = ReqProductTemplateAdd{} }
func (m *ReqProductTemplateAdd) String() string { return proto.CompactTextString(m) }
func (*ReqProductTemplateAdd) ProtoMessage()    {}
func (*ReqProductTemplateAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{4}
}

func (m *ReqProductTemplateAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProductTemplateAdd.Unmarshal(m, b)
}
func (m *ReqProductTemplateAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProductTemplateAdd.Marshal(b, m, deterministic)
}
func (m *ReqProductTemplateAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProductTemplateAdd.Merge(m, src)
}
func (m *ReqProductTemplateAdd) XXX_Size() int {
	return xxx_messageInfo_ReqProductTemplateAdd.Size(m)
}
func (m *ReqProductTemplateAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProductTemplateAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProductTemplateAdd proto.InternalMessageInfo

func (m *ReqProductTemplateAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqProductTemplateAdd) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqProductTemplateAdd) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *ReqProductTemplateAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqProductTemplateAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqProductTemplateAdd) GetFrame() string {
	if m != nil {
		return m.Frame
	}
	return ""
}

func (m *ReqProductTemplateAdd) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *ReqProductTemplateAdd) GetFps() uint32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *ReqProductTemplateAdd) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *ReqProductTemplateAdd) GetRunWidth() uint32 {
	if m != nil {
		return m.RunWidth
	}
	return 0
}

func (m *ReqProductTemplateAdd) GetRunHeight() uint32 {
	if m != nil {
		return m.RunHeight
	}
	return 0
}

func (m *ReqProductTemplateAdd) GetDesignWidth() uint32 {
	if m != nil {
		return m.DesignWidth
	}
	return 0
}

func (m *ReqProductTemplateAdd) GetDesignHeight() uint32 {
	if m != nil {
		return m.DesignHeight
	}
	return 0
}

func (m *ReqProductTemplateAdd) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ReqProductTemplateUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Env                  string   `protobuf:"bytes,6,opt,name=env,proto3" json:"env,omitempty"`
	Frame                string   `protobuf:"bytes,7,opt,name=frame,proto3" json:"frame,omitempty"`
	Asset                string   `protobuf:"bytes,8,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqProductTemplateUpdate) Reset()         { *m = ReqProductTemplateUpdate{} }
func (m *ReqProductTemplateUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqProductTemplateUpdate) ProtoMessage()    {}
func (*ReqProductTemplateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{5}
}

func (m *ReqProductTemplateUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProductTemplateUpdate.Unmarshal(m, b)
}
func (m *ReqProductTemplateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProductTemplateUpdate.Marshal(b, m, deterministic)
}
func (m *ReqProductTemplateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProductTemplateUpdate.Merge(m, src)
}
func (m *ReqProductTemplateUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqProductTemplateUpdate.Size(m)
}
func (m *ReqProductTemplateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProductTemplateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProductTemplateUpdate proto.InternalMessageInfo

func (m *ReqProductTemplateUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqProductTemplateUpdate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqProductTemplateUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqProductTemplateUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqProductTemplateUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqProductTemplateUpdate) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *ReqProductTemplateUpdate) GetFrame() string {
	if m != nil {
		return m.Frame
	}
	return ""
}

func (m *ReqProductTemplateUpdate) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type ReqProductTemplateGraph struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Fps                  uint32   `protobuf:"varint,2,opt,name=fps,proto3" json:"fps,omitempty"`
	Quality              uint32   `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	RunWidth             uint32   `protobuf:"varint,4,opt,name=runWidth,proto3" json:"runWidth,omitempty"`
	RunHeight            uint32   `protobuf:"varint,5,opt,name=runHeight,proto3" json:"runHeight,omitempty"`
	DesignWidth          uint32   `protobuf:"varint,6,opt,name=designWidth,proto3" json:"designWidth,omitempty"`
	DesignHeight         uint32   `protobuf:"varint,7,opt,name=designHeight,proto3" json:"designHeight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Operator             string   `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqProductTemplateGraph) Reset()         { *m = ReqProductTemplateGraph{} }
func (m *ReqProductTemplateGraph) String() string { return proto.CompactTextString(m) }
func (*ReqProductTemplateGraph) ProtoMessage()    {}
func (*ReqProductTemplateGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{6}
}

func (m *ReqProductTemplateGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProductTemplateGraph.Unmarshal(m, b)
}
func (m *ReqProductTemplateGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProductTemplateGraph.Marshal(b, m, deterministic)
}
func (m *ReqProductTemplateGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProductTemplateGraph.Merge(m, src)
}
func (m *ReqProductTemplateGraph) XXX_Size() int {
	return xxx_messageInfo_ReqProductTemplateGraph.Size(m)
}
func (m *ReqProductTemplateGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProductTemplateGraph.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProductTemplateGraph proto.InternalMessageInfo

func (m *ReqProductTemplateGraph) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqProductTemplateGraph) GetFps() uint32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *ReqProductTemplateGraph) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *ReqProductTemplateGraph) GetRunWidth() uint32 {
	if m != nil {
		return m.RunWidth
	}
	return 0
}

func (m *ReqProductTemplateGraph) GetRunHeight() uint32 {
	if m != nil {
		return m.RunHeight
	}
	return 0
}

func (m *ReqProductTemplateGraph) GetDesignWidth() uint32 {
	if m != nil {
		return m.DesignWidth
	}
	return 0
}

func (m *ReqProductTemplateGraph) GetDesignHeight() uint32 {
	if m != nil {
		return m.DesignHeight
	}
	return 0
}

func (m *ReqProductTemplateGraph) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ReqProductTemplateGraph) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyProductTemplateInfo struct {
	Status               *ReplyStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *ProductTemplateInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReplyProductTemplateInfo) Reset()         { *m = ReplyProductTemplateInfo{} }
func (m *ReplyProductTemplateInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyProductTemplateInfo) ProtoMessage()    {}
func (*ReplyProductTemplateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{7}
}

func (m *ReplyProductTemplateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyProductTemplateInfo.Unmarshal(m, b)
}
func (m *ReplyProductTemplateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyProductTemplateInfo.Marshal(b, m, deterministic)
}
func (m *ReplyProductTemplateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyProductTemplateInfo.Merge(m, src)
}
func (m *ReplyProductTemplateInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyProductTemplateInfo.Size(m)
}
func (m *ReplyProductTemplateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyProductTemplateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyProductTemplateInfo proto.InternalMessageInfo

func (m *ReplyProductTemplateInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyProductTemplateInfo) GetInfo() *ProductTemplateInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyProductTemplateResult struct {
	Status               *ReplyStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *ProductTemplateResult `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ReplyProductTemplateResult) Reset()         { *m = ReplyProductTemplateResult{} }
func (m *ReplyProductTemplateResult) String() string { return proto.CompactTextString(m) }
func (*ReplyProductTemplateResult) ProtoMessage()    {}
func (*ReplyProductTemplateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{8}
}

func (m *ReplyProductTemplateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyProductTemplateResult.Unmarshal(m, b)
}
func (m *ReplyProductTemplateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyProductTemplateResult.Marshal(b, m, deterministic)
}
func (m *ReplyProductTemplateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyProductTemplateResult.Merge(m, src)
}
func (m *ReplyProductTemplateResult) XXX_Size() int {
	return xxx_messageInfo_ReplyProductTemplateResult.Size(m)
}
func (m *ReplyProductTemplateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyProductTemplateResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyProductTemplateResult proto.InternalMessageInfo

func (m *ReplyProductTemplateResult) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyProductTemplateResult) GetInfo() *ProductTemplateResult {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyProductTemplateList struct {
	Status               *ReplyStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32                 `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32                 `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*ProductTemplateInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ReplyProductTemplateList) Reset()         { *m = ReplyProductTemplateList{} }
func (m *ReplyProductTemplateList) String() string { return proto.CompactTextString(m) }
func (*ReplyProductTemplateList) ProtoMessage()    {}
func (*ReplyProductTemplateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{9}
}

func (m *ReplyProductTemplateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyProductTemplateList.Unmarshal(m, b)
}
func (m *ReplyProductTemplateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyProductTemplateList.Marshal(b, m, deterministic)
}
func (m *ReplyProductTemplateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyProductTemplateList.Merge(m, src)
}
func (m *ReplyProductTemplateList) XXX_Size() int {
	return xxx_messageInfo_ReplyProductTemplateList.Size(m)
}
func (m *ReplyProductTemplateList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyProductTemplateList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyProductTemplateList proto.InternalMessageInfo

func (m *ReplyProductTemplateList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyProductTemplateList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyProductTemplateList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyProductTemplateList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyProductTemplateList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyProductTemplateList) GetList() []*ProductTemplateInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyProductTemplateResults struct {
	Status               *ReplyStatus             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32                   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32                   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32                   `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*ProductTemplateResult `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ReplyProductTemplateResults) Reset()         { *m = ReplyProductTemplateResults{} }
func (m *ReplyProductTemplateResults) String() string { return proto.CompactTextString(m) }
func (*ReplyProductTemplateResults) ProtoMessage()    {}
func (*ReplyProductTemplateResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd483da19dc9a67, []int{10}
}

func (m *ReplyProductTemplateResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyProductTemplateResults.Unmarshal(m, b)
}
func (m *ReplyProductTemplateResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyProductTemplateResults.Marshal(b, m, deterministic)
}
func (m *ReplyProductTemplateResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyProductTemplateResults.Merge(m, src)
}
func (m *ReplyProductTemplateResults) XXX_Size() int {
	return xxx_messageInfo_ReplyProductTemplateResults.Size(m)
}
func (m *ReplyProductTemplateResults) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyProductTemplateResults.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyProductTemplateResults proto.InternalMessageInfo

func (m *ReplyProductTemplateResults) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyProductTemplateResults) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyProductTemplateResults) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyProductTemplateResults) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyProductTemplateResults) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyProductTemplateResults) GetList() []*ProductTemplateResult {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductTemplateInfo)(nil), "omo.msp.favorite.ProductTemplateInfo")
	proto.RegisterType((*ProductTemplateResult)(nil), "omo.msp.favorite.ProductTemplateResult")
	proto.RegisterType((*ReferenceInfo)(nil), "omo.msp.favorite.ReferenceInfo")
	proto.RegisterType((*ProductGraph)(nil), "omo.msp.favorite.ProductGraph")
	proto.RegisterType((*ReqProductTemplateAdd)(nil), "omo.msp.favorite.ReqProductTemplateAdd")
	proto.RegisterType((*ReqProductTemplateUpdate)(nil), "omo.msp.favorite.ReqProductTemplateUpdate")
	proto.RegisterType((*ReqProductTemplateGraph)(nil), "omo.msp.favorite.ReqProductTemplateGraph")
	proto.RegisterType((*ReplyProductTemplateInfo)(nil), "omo.msp.favorite.ReplyProductTemplateInfo")
	proto.RegisterType((*ReplyProductTemplateResult)(nil), "omo.msp.favorite.ReplyProductTemplateResult")
	proto.RegisterType((*ReplyProductTemplateList)(nil), "omo.msp.favorite.ReplyProductTemplateList")
	proto.RegisterType((*ReplyProductTemplateResults)(nil), "omo.msp.favorite.ReplyProductTemplateResults")
}

func init() {
	proto.RegisterFile("proto/favorite/template.proto", fileDescriptor_4fd483da19dc9a67)
}

var fileDescriptor_4fd483da19dc9a67 = []byte{
	// 1089 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0xad, 0x93, 0x35, 0x3a, 0xfc, 0xc6, 0xc6, 0x76, 0x08, 0xf9, 0x8f, 0x2d, 0x10, 0x2d,
	0xa2, 0x06, 0xad, 0x03, 0xb8, 0xe9, 0x45, 0x90, 0x8b, 0x22, 0x29, 0x50, 0x37, 0x40, 0x8b, 0x04,
	0x74, 0x83, 0x00, 0x45, 0x8b, 0x82, 0x16, 0x47, 0x32, 0x61, 0x8a, 0x4b, 0xef, 0x2e, 0x15, 0x08,
	0x7d, 0x84, 0xf6, 0xa2, 0x6f, 0xd1, 0x17, 0xe9, 0x13, 0xb4, 0xaf, 0x90, 0x9b, 0x5e, 0xf7, 0x05,
	0x8a, 0x3d, 0x48, 0x24, 0x65, 0x4a, 0x94, 0x7d, 0x55, 0xa0, 0x77, 0x3b, 0xb3, 0xdf, 0xcc, 0xce,
	0x7e, 0xdf, 0xec, 0x50, 0x82, 0x07, 0x31, 0xa3, 0x82, 0x3e, 0x1e, 0x79, 0x53, 0xca, 0x02, 0x81,
	0x8f, 0x05, 0x4e, 0xe2, 0xd0, 0x13, 0x78, 0xa2, 0xfc, 0x64, 0x97, 0x4e, 0xe8, 0xc9, 0x84, 0xc7,
	0x27, 0x73, 0x40, 0xef, 0x70, 0x29, 0x60, 0x48, 0x27, 0x13, 0x1a, 0x69, 0xb8, 0xf3, 0x5b, 0x15,
	0xee, 0xbd, 0x66, 0xd4, 0x4f, 0x86, 0xe2, 0x5b, 0x93, 0xe8, 0x65, 0x34, 0xa2, 0x64, 0x17, 0x2a,
	0x49, 0xe0, 0xdb, 0x56, 0xdf, 0x1a, 0x34, 0x5d, 0xb9, 0x24, 0x5d, 0xd8, 0x0e, 0x7c, 0x7b, 0xbb,
	0x6f, 0x0d, 0xaa, 0xee, 0x76, 0xe0, 0x13, 0x1b, 0x1a, 0x43, 0x86, 0x9e, 0x40, 0xdf, 0xae, 0xf4,
	0xad, 0x41, 0xc5, 0x9d, 0x9b, 0x72, 0x27, 0x89, 0x7d, 0xb5, 0x53, 0xd5, 0x3b, 0xc6, 0x5c, 0xc4,
	0x50, 0x66, 0xd7, 0x54, 0xe6, 0xb9, 0x49, 0x7a, 0xb0, 0x43, 0x63, 0x64, 0x6a, 0xab, 0xae, 0xb6,
	0x16, 0x36, 0x21, 0x50, 0x8d, 0xbc, 0x09, 0xda, 0x0d, 0xe5, 0x57, 0x6b, 0x89, 0xbf, 0xc2, 0xd9,
	0x3b, 0xca, 0x7c, 0x6e, 0xef, 0x68, 0xfc, 0xdc, 0x26, 0x07, 0x50, 0xe7, 0xc2, 0x13, 0x09, 0xb7,
	0xa1, 0x6f, 0x0d, 0x3a, 0xae, 0xb1, 0xa4, 0x9f, 0xe1, 0xc4, 0x63, 0x57, 0x76, 0x4b, 0x45, 0x18,
	0x8b, 0xec, 0x41, 0x6d, 0xc4, 0xe4, 0x01, 0x6d, 0xe5, 0xd6, 0x86, 0xf4, 0x7a, 0x9c, 0xa3, 0xb0,
	0x3b, 0xda, 0xab, 0x0c, 0xc9, 0x0b, 0x46, 0x53, 0xbb, 0xab, 0x79, 0xc1, 0x68, 0x4a, 0x9e, 0x40,
	0x6d, 0xcc, 0xbc, 0xf8, 0xd2, 0xbe, 0xd7, 0xb7, 0x06, 0xad, 0xd3, 0xa3, 0x93, 0x65, 0x01, 0x4e,
	0x0c, 0xbf, 0x67, 0x12, 0xe5, 0x6a, 0x30, 0x79, 0x0a, 0x0d, 0x1f, 0x63, 0x8c, 0x7c, 0x6e, 0xef,
	0xf5, 0x2b, 0x83, 0xd6, 0xe9, 0xf1, 0xcd, 0x38, 0x17, 0x47, 0xc8, 0x30, 0x1a, 0x2a, 0x45, 0xdc,
	0x39, 0x9e, 0x7c, 0x0e, 0x70, 0x41, 0xa9, 0x08, 0xa9, 0xe7, 0x23, 0xb3, 0xf7, 0x37, 0x8b, 0xce,
	0x84, 0x90, 0x27, 0xd0, 0x98, 0x50, 0x3f, 0x09, 0x91, 0xdb, 0xc7, 0x2a, 0xba, 0x57, 0x50, 0xb3,
	0x17, 0x30, 0x7d, 0xac, 0x81, 0x3a, 0x7f, 0x56, 0x60, 0x7f, 0xa9, 0x53, 0x5c, 0xe4, 0x49, 0x28,
	0xfe, 0x53, 0xbd, 0xf2, 0x7f, 0x68, 0xea, 0x02, 0xbf, 0x18, 0x8d, 0xed, 0x7d, 0xb5, 0x95, 0x3a,
	0xc8, 0x07, 0xd0, 0x49, 0x79, 0x96, 0x88, 0x03, 0x85, 0xc8, 0x3b, 0xc9, 0x11, 0x80, 0xd1, 0x52,
	0x42, 0xee, 0x2b, 0x48, 0xc6, 0x93, 0x76, 0xd4, 0xd1, 0x6d, 0x3a, 0xea, 0x6e, 0xaa, 0xfe, 0x04,
	0x9d, 0x5c, 0xa3, 0x48, 0x02, 0xaf, 0x82, 0x48, 0xab, 0xd9, 0x71, 0xd5, 0x5a, 0x0a, 0x4c, 0xd9,
	0x58, 0xe9, 0xd9, 0x74, 0xe5, 0x72, 0x41, 0x73, 0x25, 0x43, 0xb3, 0x0d, 0x8d, 0x29, 0x32, 0x1e,
	0xd0, 0x48, 0x49, 0xd9, 0x74, 0xe7, 0xa6, 0x24, 0xf3, 0x1d, 0x06, 0xe3, 0x4b, 0x61, 0x94, 0x34,
	0x96, 0xf3, 0x87, 0x05, 0xed, 0xec, 0x55, 0x64, 0x8a, 0xeb, 0xc4, 0x0b, 0x03, 0x31, 0x33, 0xe7,
	0xcf, 0x4d, 0x59, 0xc2, 0x28, 0xe6, 0xaa, 0x84, 0x8e, 0x2b, 0x97, 0x52, 0x55, 0x96, 0x44, 0x6f,
	0x03, 0x5f, 0x5c, 0xaa, 0x32, 0x3a, 0xee, 0xc2, 0x96, 0x2a, 0xb1, 0x24, 0xfa, 0x4a, 0x9f, 0x59,
	0x55, 0x9b, 0xa9, 0x83, 0xf4, 0xa1, 0xe5, 0x23, 0x0f, 0xc6, 0x26, 0xb8, 0xa6, 0xf6, 0xb3, 0x2e,
	0xe2, 0x40, 0x5b, 0x9b, 0x26, 0x45, 0x5d, 0x41, 0x72, 0xbe, 0xcc, 0xa5, 0x1a, 0xba, 0x73, 0xcc,
	0xa5, 0xfe, 0xde, 0x86, 0x7d, 0x17, 0xaf, 0x97, 0x9e, 0xca, 0x73, 0xdf, 0x5f, 0x90, 0x66, 0x65,
	0x48, 0xdb, 0x85, 0xca, 0x15, 0xce, 0xe6, 0xd4, 0x5e, 0xe1, 0x6c, 0x3e, 0x61, 0xaa, 0xe9, 0x84,
	0xc9, 0xf6, 0x7b, 0x6d, 0xa9, 0xdf, 0xd3, 0x3e, 0xad, 0x17, 0xcf, 0xb4, 0x46, 0xe1, 0x4c, 0xdb,
	0x59, 0x9a, 0x69, 0x92, 0x5b, 0x48, 0xb9, 0xcd, 0xe8, 0xd0, 0xca, 0xeb, 0x90, 0x65, 0xbd, 0xbd,
	0x8e, 0xf5, 0x4e, 0x09, 0xeb, 0xdd, 0x72, 0xd6, 0xff, 0xb7, 0x96, 0xf5, 0xdd, 0x1c, 0xeb, 0xbf,
	0x5b, 0x60, 0xdf, 0x64, 0xfd, 0x8d, 0x7a, 0x99, 0x05, 0x03, 0xea, 0x26, 0xed, 0x45, 0x1d, 0x9d,
	0x92, 0x5b, 0xcd, 0x91, 0xbb, 0x4e, 0x10, 0x23, 0x5f, 0x3d, 0x95, 0xef, 0x16, 0x52, 0x38, 0x3f,
	0x6f, 0xc3, 0xfd, 0x9b, 0xd7, 0xd0, 0x8f, 0xa3, 0xf0, 0x16, 0x4b, 0x8f, 0x22, 0x23, 0x5c, 0x65,
	0xb5, 0x70, 0xd5, 0x75, 0xc2, 0xd5, 0x4a, 0x84, 0xab, 0x97, 0x0b, 0xd7, 0x58, 0x2b, 0xdc, 0x4e,
	0x56, 0xb8, 0x1c, 0x97, 0xcd, 0x3c, 0x97, 0xce, 0x2f, 0x4a, 0xd4, 0x38, 0x9c, 0x15, 0xfd, 0x42,
	0xf9, 0x6c, 0x31, 0xb9, 0x2d, 0x35, 0x26, 0x1f, 0x14, 0x7d, 0x02, 0xe3, 0x70, 0x76, 0xae, 0x40,
	0x8b, 0xc1, 0xfe, 0x14, 0xaa, 0x41, 0x34, 0xa2, 0x8a, 0xb4, 0xd6, 0xe9, 0x87, 0x2b, 0x67, 0x6b,
	0xf6, 0x2c, 0x57, 0x85, 0x38, 0xbf, 0x5a, 0xd0, 0x2b, 0x2a, 0xc7, 0x7c, 0x06, 0xef, 0x58, 0xd0,
	0xb3, 0x5c, 0x41, 0x0f, 0x4b, 0x0b, 0xd2, 0xa7, 0x99, 0x92, 0xde, 0xaf, 0x60, 0xe8, 0xeb, 0x80,
	0xdf, 0xb9, 0xa0, 0x3d, 0xa8, 0x09, 0x2a, 0xbc, 0xd0, 0xf4, 0x95, 0x36, 0xa4, 0x37, 0xf6, 0xc6,
	0xc8, 0x4d, 0x5f, 0x69, 0x43, 0xbe, 0x1a, 0xb9, 0x30, 0x1d, 0xa5, 0xd6, 0x52, 0xe9, 0x28, 0x99,
	0x5c, 0x20, 0x33, 0xad, 0x64, 0x2c, 0xc9, 0x7c, 0x18, 0x70, 0xf9, 0x70, 0x2b, 0xb7, 0x60, 0x5e,
	0x86, 0x38, 0x7f, 0x59, 0x70, 0xb8, 0x9a, 0x79, 0xfe, 0x6f, 0xbb, 0xe9, 0xb3, 0xdc, 0x4d, 0x37,
	0x97, 0x54, 0x06, 0x9d, 0xbe, 0x6f, 0xc0, 0xc1, 0xd2, 0xfe, 0x39, 0xb2, 0x69, 0x30, 0x44, 0xf2,
	0x23, 0xd4, 0x9f, 0xfb, 0xfe, 0xab, 0x08, 0xc9, 0xc3, 0xa2, 0x0b, 0x16, 0x7c, 0x73, 0x7a, 0x8f,
	0x56, 0x30, 0x51, 0xc0, 0xb5, 0xb3, 0x45, 0xde, 0x40, 0xfd, 0x0c, 0x85, 0x3c, 0xa0, 0x90, 0xc1,
	0xeb, 0x04, 0xb9, 0x90, 0xd0, 0x5b, 0xa6, 0xfd, 0x1e, 0x5a, 0x67, 0x28, 0x5e, 0xcc, 0xbe, 0x0c,
	0x42, 0x81, 0x8c, 0x1c, 0xaf, 0xcc, 0xad, 0x01, 0x9b, 0x66, 0x97, 0x4d, 0xee, 0x6c, 0x91, 0x73,
	0x68, 0x9f, 0xa1, 0x90, 0xd2, 0x06, 0x5c, 0x04, 0xc3, 0xf2, 0xf4, 0xfd, 0x35, 0xdd, 0xa1, 0x52,
	0x38, 0x5b, 0xe4, 0x35, 0x74, 0xf5, 0xc7, 0x63, 0x83, 0xaa, 0x35, 0xb0, 0x77, 0xb8, 0x22, 0xad,
	0x21, 0xe1, 0x2d, 0x80, 0xc9, 0xe8, 0x71, 0x24, 0x8f, 0x36, 0x11, 0x70, 0xd3, 0xc4, 0x2d, 0x0d,
	0xd4, 0x9f, 0x89, 0x8f, 0x36, 0xc9, 0xac, 0xa0, 0x65, 0x89, 0xbf, 0x81, 0xb6, 0x4e, 0xac, 0x9f,
	0x0d, 0x39, 0x5a, 0xc9, 0x80, 0x04, 0x94, 0xd6, 0xf9, 0x12, 0x9a, 0x2e, 0x4e, 0xe8, 0x14, 0x37,
	0xe8, 0xaf, 0x92, 0x54, 0x3f, 0x28, 0xc9, 0x5d, 0x0c, 0xd1, 0xe3, 0xf8, 0x2a, 0x2a, 0xcb, 0xf6,
	0xf1, 0x66, 0xfd, 0xa4, 0x9f, 0xa1, 0xb3, 0x45, 0x2e, 0xa0, 0x9b, 0xa6, 0x57, 0xa3, 0xb4, 0xb4,
	0xa7, 0x3e, 0xb9, 0xcd, 0x11, 0xdc, 0xd9, 0x7a, 0xb1, 0xfb, 0x5d, 0x37, 0xff, 0xbf, 0xfc, 0xa2,
	0xae, 0xec, 0x4f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x02, 0x85, 0xdf, 0x1c, 0xe1, 0x0f, 0x00,
	0x00,
}
